
namespace MTAStudentManagementSystem.GUI.UserControl
{
    partial class UCGiangDuong
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UCGiangDuong));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.dgvGiangDuong = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bHuyCS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bLuuCS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bSuaCS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bThemCS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bXoaCS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbMaGiangDuongCS = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbMoTaGiangDuongCS = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbMoTaGiangDuongTK = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbMaGiangDuongTK = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dgvGiangDuong)).BeginInit();
            this.bunifuGroupBox2.SuspendLayout();
            this.bunifuGroupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // dgvGiangDuong
            // 
            this.dgvGiangDuong.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgvGiangDuong.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvGiangDuong.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvGiangDuong.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvGiangDuong.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvGiangDuong.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvGiangDuong.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvGiangDuong.ColumnHeadersHeight = 40;
            this.dgvGiangDuong.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvGiangDuong.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvGiangDuong.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvGiangDuong.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvGiangDuong.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvGiangDuong.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvGiangDuong.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvGiangDuong.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvGiangDuong.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvGiangDuong.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvGiangDuong.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvGiangDuong.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvGiangDuong.CurrentTheme.Name = null;
            this.dgvGiangDuong.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvGiangDuong.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvGiangDuong.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvGiangDuong.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvGiangDuong.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvGiangDuong.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvGiangDuong.EnableHeadersVisualStyles = false;
            this.dgvGiangDuong.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvGiangDuong.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvGiangDuong.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvGiangDuong.HeaderForeColor = System.Drawing.Color.White;
            this.dgvGiangDuong.Location = new System.Drawing.Point(3, 134);
            this.dgvGiangDuong.Name = "dgvGiangDuong";
            this.dgvGiangDuong.RowHeadersVisible = false;
            this.dgvGiangDuong.RowHeadersWidth = 51;
            this.dgvGiangDuong.RowTemplate.Height = 40;
            this.dgvGiangDuong.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvGiangDuong.Size = new System.Drawing.Size(600, 443);
            this.dgvGiangDuong.TabIndex = 6;
            this.dgvGiangDuong.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BackColor = System.Drawing.Color.White;
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 1;
            this.bunifuGroupBox2.Controls.Add(this.bHuyCS);
            this.bunifuGroupBox2.Controls.Add(this.bLuuCS);
            this.bunifuGroupBox2.Controls.Add(this.bSuaCS);
            this.bunifuGroupBox2.Controls.Add(this.bThemCS);
            this.bunifuGroupBox2.Controls.Add(this.bXoaCS);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel3);
            this.bunifuGroupBox2.Controls.Add(this.tbMaGiangDuongCS);
            this.bunifuGroupBox2.Controls.Add(this.tbMoTaGiangDuongCS);
            this.bunifuGroupBox2.Controls.Add(this.bunifuLabel4);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox2.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(609, 3);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(418, 574);
            this.bunifuGroupBox2.TabIndex = 5;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Chỉnh sửa";
            // 
            // bHuyCS
            // 
            this.bHuyCS.AllowAnimations = true;
            this.bHuyCS.AllowMouseEffects = true;
            this.bHuyCS.AllowToggling = false;
            this.bHuyCS.AnimationSpeed = 200;
            this.bHuyCS.AutoGenerateColors = true;
            this.bHuyCS.AutoRoundBorders = false;
            this.bHuyCS.AutoSizeLeftIcon = true;
            this.bHuyCS.AutoSizeRightIcon = true;
            this.bHuyCS.BackColor = System.Drawing.Color.Transparent;
            this.bHuyCS.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bHuyCS.BackgroundImage")));
            this.bHuyCS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.ButtonText = "Huỷ";
            this.bHuyCS.ButtonTextMarginLeft = 15;
            this.bHuyCS.ColorContrastOnClick = 45;
            this.bHuyCS.ColorContrastOnHover = 45;
            this.bHuyCS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bHuyCS.CustomizableEdges = borderEdges1;
            this.bHuyCS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bHuyCS.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bHuyCS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bHuyCS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bHuyCS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bHuyCS.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.bHuyCS.ForeColor = System.Drawing.Color.White;
            this.bHuyCS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bHuyCS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bHuyCS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bHuyCS.IconMarginLeft = 11;
            this.bHuyCS.IconPadding = 10;
            this.bHuyCS.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bHuyCS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bHuyCS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bHuyCS.IconSize = 25;
            this.bHuyCS.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.IdleBorderRadius = 5;
            this.bHuyCS.IdleBorderThickness = 1;
            this.bHuyCS.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bHuyCS.IdleIconLeftImage")));
            this.bHuyCS.IdleIconRightImage = null;
            this.bHuyCS.IndicateFocus = false;
            this.bHuyCS.Location = new System.Drawing.Point(192, 339);
            this.bHuyCS.Name = "bHuyCS";
            this.bHuyCS.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bHuyCS.OnDisabledState.BorderRadius = 5;
            this.bHuyCS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.OnDisabledState.BorderThickness = 1;
            this.bHuyCS.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bHuyCS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bHuyCS.OnDisabledState.IconLeftImage = null;
            this.bHuyCS.OnDisabledState.IconRightImage = null;
            this.bHuyCS.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(134)))), ((int)(((byte)(147)))));
            this.bHuyCS.onHoverState.BorderRadius = 5;
            this.bHuyCS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.onHoverState.BorderThickness = 1;
            this.bHuyCS.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(134)))), ((int)(((byte)(147)))));
            this.bHuyCS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bHuyCS.onHoverState.IconLeftImage = null;
            this.bHuyCS.onHoverState.IconRightImage = null;
            this.bHuyCS.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.OnIdleState.BorderRadius = 5;
            this.bHuyCS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.OnIdleState.BorderThickness = 1;
            this.bHuyCS.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bHuyCS.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnHuyKH.OnIdleState.IconLeftImage")));
            this.bHuyCS.OnIdleState.IconRightImage = null;
            this.bHuyCS.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(19)))), ((int)(((byte)(33)))));
            this.bHuyCS.OnPressedState.BorderRadius = 5;
            this.bHuyCS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.OnPressedState.BorderThickness = 1;
            this.bHuyCS.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(19)))), ((int)(((byte)(33)))));
            this.bHuyCS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bHuyCS.OnPressedState.IconLeftImage = null;
            this.bHuyCS.OnPressedState.IconRightImage = null;
            this.bHuyCS.Size = new System.Drawing.Size(118, 45);
            this.bHuyCS.TabIndex = 30;
            this.bHuyCS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bHuyCS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bHuyCS.TextMarginLeft = 15;
            this.bHuyCS.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bHuyCS.UseDefaultRadiusAndThickness = true;
            // 
            // bLuuCS
            // 
            this.bLuuCS.AllowAnimations = true;
            this.bLuuCS.AllowMouseEffects = true;
            this.bLuuCS.AllowToggling = false;
            this.bLuuCS.AnimationSpeed = 200;
            this.bLuuCS.AutoGenerateColors = true;
            this.bLuuCS.AutoRoundBorders = false;
            this.bLuuCS.AutoSizeLeftIcon = true;
            this.bLuuCS.AutoSizeRightIcon = true;
            this.bLuuCS.BackColor = System.Drawing.Color.Transparent;
            this.bLuuCS.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bLuuCS.BackgroundImage")));
            this.bLuuCS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.ButtonText = "Lưu";
            this.bLuuCS.ButtonTextMarginLeft = 15;
            this.bLuuCS.ColorContrastOnClick = 45;
            this.bLuuCS.ColorContrastOnHover = 45;
            this.bLuuCS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bLuuCS.CustomizableEdges = borderEdges2;
            this.bLuuCS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bLuuCS.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bLuuCS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bLuuCS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bLuuCS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bLuuCS.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.bLuuCS.ForeColor = System.Drawing.Color.White;
            this.bLuuCS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bLuuCS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bLuuCS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bLuuCS.IconMarginLeft = 11;
            this.bLuuCS.IconPadding = 10;
            this.bLuuCS.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bLuuCS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bLuuCS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bLuuCS.IconSize = 25;
            this.bLuuCS.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.IdleBorderRadius = 5;
            this.bLuuCS.IdleBorderThickness = 1;
            this.bLuuCS.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bLuuCS.IdleIconLeftImage")));
            this.bLuuCS.IdleIconRightImage = null;
            this.bLuuCS.IndicateFocus = false;
            this.bLuuCS.Location = new System.Drawing.Point(68, 339);
            this.bLuuCS.Name = "bLuuCS";
            this.bLuuCS.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bLuuCS.OnDisabledState.BorderRadius = 5;
            this.bLuuCS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.OnDisabledState.BorderThickness = 1;
            this.bLuuCS.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bLuuCS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bLuuCS.OnDisabledState.IconLeftImage = null;
            this.bLuuCS.OnDisabledState.IconRightImage = null;
            this.bLuuCS.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(152)))), ((int)(((byte)(181)))));
            this.bLuuCS.onHoverState.BorderRadius = 5;
            this.bLuuCS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.onHoverState.BorderThickness = 1;
            this.bLuuCS.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(152)))), ((int)(((byte)(181)))));
            this.bLuuCS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bLuuCS.onHoverState.IconLeftImage = null;
            this.bLuuCS.onHoverState.IconRightImage = null;
            this.bLuuCS.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.OnIdleState.BorderRadius = 5;
            this.bLuuCS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.OnIdleState.BorderThickness = 1;
            this.bLuuCS.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bLuuCS.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnLuuKH.OnIdleState.IconLeftImage")));
            this.bLuuCS.OnIdleState.IconRightImage = null;
            this.bLuuCS.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(37)))), ((int)(((byte)(67)))));
            this.bLuuCS.OnPressedState.BorderRadius = 5;
            this.bLuuCS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.OnPressedState.BorderThickness = 1;
            this.bLuuCS.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(37)))), ((int)(((byte)(67)))));
            this.bLuuCS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bLuuCS.OnPressedState.IconLeftImage = null;
            this.bLuuCS.OnPressedState.IconRightImage = null;
            this.bLuuCS.Size = new System.Drawing.Size(118, 45);
            this.bLuuCS.TabIndex = 31;
            this.bLuuCS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bLuuCS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bLuuCS.TextMarginLeft = 15;
            this.bLuuCS.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bLuuCS.UseDefaultRadiusAndThickness = true;
            // 
            // bSuaCS
            // 
            this.bSuaCS.AllowAnimations = true;
            this.bSuaCS.AllowMouseEffects = true;
            this.bSuaCS.AllowToggling = false;
            this.bSuaCS.AnimationSpeed = 200;
            this.bSuaCS.AutoGenerateColors = true;
            this.bSuaCS.AutoRoundBorders = false;
            this.bSuaCS.AutoSizeLeftIcon = true;
            this.bSuaCS.AutoSizeRightIcon = true;
            this.bSuaCS.BackColor = System.Drawing.Color.Transparent;
            this.bSuaCS.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bSuaCS.BackgroundImage")));
            this.bSuaCS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.ButtonText = "Sửa";
            this.bSuaCS.ButtonTextMarginLeft = 15;
            this.bSuaCS.ColorContrastOnClick = 45;
            this.bSuaCS.ColorContrastOnHover = 45;
            this.bSuaCS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bSuaCS.CustomizableEdges = borderEdges3;
            this.bSuaCS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bSuaCS.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bSuaCS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bSuaCS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bSuaCS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bSuaCS.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.bSuaCS.ForeColor = System.Drawing.Color.White;
            this.bSuaCS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bSuaCS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bSuaCS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bSuaCS.IconMarginLeft = 11;
            this.bSuaCS.IconPadding = 10;
            this.bSuaCS.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bSuaCS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bSuaCS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bSuaCS.IconSize = 25;
            this.bSuaCS.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.IdleBorderRadius = 5;
            this.bSuaCS.IdleBorderThickness = 1;
            this.bSuaCS.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bSuaCS.IdleIconLeftImage")));
            this.bSuaCS.IdleIconRightImage = null;
            this.bSuaCS.IndicateFocus = false;
            this.bSuaCS.Location = new System.Drawing.Point(151, 271);
            this.bSuaCS.Name = "bSuaCS";
            this.bSuaCS.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.bSuaCS.OnDisabledState.BorderRadius = 5;
            this.bSuaCS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.OnDisabledState.BorderThickness = 1;
            this.bSuaCS.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bSuaCS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bSuaCS.OnDisabledState.IconLeftImage = null;
            this.bSuaCS.OnDisabledState.IconRightImage = null;
            this.bSuaCS.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(159)))), ((int)(((byte)(217)))), ((int)(((byte)(235)))));
            this.bSuaCS.onHoverState.BorderRadius = 5;
            this.bSuaCS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.onHoverState.BorderThickness = 1;
            this.bSuaCS.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(159)))), ((int)(((byte)(217)))), ((int)(((byte)(235)))));
            this.bSuaCS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bSuaCS.onHoverState.IconLeftImage = null;
            this.bSuaCS.onHoverState.IconRightImage = null;
            this.bSuaCS.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.OnIdleState.BorderRadius = 5;
            this.bSuaCS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.OnIdleState.BorderThickness = 1;
            this.bSuaCS.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bSuaCS.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSuaNV.OnIdleState.IconLeftImage")));
            this.bSuaCS.OnIdleState.IconRightImage = null;
            this.bSuaCS.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(102)))), ((int)(((byte)(120)))));
            this.bSuaCS.OnPressedState.BorderRadius = 5;
            this.bSuaCS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.OnPressedState.BorderThickness = 1;
            this.bSuaCS.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(102)))), ((int)(((byte)(120)))));
            this.bSuaCS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bSuaCS.OnPressedState.IconLeftImage = null;
            this.bSuaCS.OnPressedState.IconRightImage = null;
            this.bSuaCS.Size = new System.Drawing.Size(110, 45);
            this.bSuaCS.TabIndex = 27;
            this.bSuaCS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bSuaCS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bSuaCS.TextMarginLeft = 15;
            this.bSuaCS.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bSuaCS.UseDefaultRadiusAndThickness = true;
            // 
            // bThemCS
            // 
            this.bThemCS.AllowAnimations = true;
            this.bThemCS.AllowMouseEffects = true;
            this.bThemCS.AllowToggling = false;
            this.bThemCS.AnimationSpeed = 200;
            this.bThemCS.AutoGenerateColors = true;
            this.bThemCS.AutoRoundBorders = false;
            this.bThemCS.AutoSizeLeftIcon = true;
            this.bThemCS.AutoSizeRightIcon = true;
            this.bThemCS.BackColor = System.Drawing.Color.Transparent;
            this.bThemCS.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.bThemCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bThemCS.BackgroundImage")));
            this.bThemCS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bThemCS.ButtonText = "Thêm";
            this.bThemCS.ButtonTextMarginLeft = 15;
            this.bThemCS.ColorContrastOnClick = 45;
            this.bThemCS.ColorContrastOnHover = 45;
            this.bThemCS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bThemCS.CustomizableEdges = borderEdges4;
            this.bThemCS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bThemCS.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bThemCS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bThemCS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bThemCS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bThemCS.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.bThemCS.ForeColor = System.Drawing.Color.White;
            this.bThemCS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bThemCS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bThemCS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bThemCS.IconMarginLeft = 11;
            this.bThemCS.IconPadding = 10;
            this.bThemCS.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bThemCS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bThemCS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bThemCS.IconSize = 25;
            this.bThemCS.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.bThemCS.IdleBorderRadius = 5;
            this.bThemCS.IdleBorderThickness = 1;
            this.bThemCS.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.bThemCS.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bThemCS.IdleIconLeftImage")));
            this.bThemCS.IdleIconRightImage = null;
            this.bThemCS.IndicateFocus = false;
            this.bThemCS.Location = new System.Drawing.Point(35, 271);
            this.bThemCS.Name = "bThemCS";
            this.bThemCS.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bThemCS.OnDisabledState.BorderRadius = 5;
            this.bThemCS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bThemCS.OnDisabledState.BorderThickness = 1;
            this.bThemCS.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bThemCS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bThemCS.OnDisabledState.IconLeftImage = null;
            this.bThemCS.OnDisabledState.IconRightImage = null;
            this.bThemCS.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            this.bThemCS.onHoverState.BorderRadius = 5;
            this.bThemCS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bThemCS.onHoverState.BorderThickness = 1;
            this.bThemCS.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(211)))), ((int)(((byte)(161)))));
            this.bThemCS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bThemCS.onHoverState.IconLeftImage = null;
            this.bThemCS.onHoverState.IconRightImage = null;
            this.bThemCS.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.bThemCS.OnIdleState.BorderRadius = 5;
            this.bThemCS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bThemCS.OnIdleState.BorderThickness = 1;
            this.bThemCS.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(175)))), ((int)(((byte)(85)))));
            this.bThemCS.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bThemCS.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnThemNV.OnIdleState.IconLeftImage")));
            this.bThemCS.OnIdleState.IconRightImage = null;
            this.bThemCS.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            this.bThemCS.OnPressedState.BorderRadius = 5;
            this.bThemCS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bThemCS.OnPressedState.BorderThickness = 1;
            this.bThemCS.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(47)))), ((int)(((byte)(96)))), ((int)(((byte)(46)))));
            this.bThemCS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bThemCS.OnPressedState.IconLeftImage = null;
            this.bThemCS.OnPressedState.IconRightImage = null;
            this.bThemCS.Size = new System.Drawing.Size(110, 45);
            this.bThemCS.TabIndex = 28;
            this.bThemCS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bThemCS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bThemCS.TextMarginLeft = 15;
            this.bThemCS.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bThemCS.UseDefaultRadiusAndThickness = true;
            // 
            // bXoaCS
            // 
            this.bXoaCS.AllowAnimations = true;
            this.bXoaCS.AllowMouseEffects = true;
            this.bXoaCS.AllowToggling = false;
            this.bXoaCS.AnimationSpeed = 200;
            this.bXoaCS.AutoGenerateColors = true;
            this.bXoaCS.AutoRoundBorders = false;
            this.bXoaCS.AutoSizeLeftIcon = true;
            this.bXoaCS.AutoSizeRightIcon = true;
            this.bXoaCS.BackColor = System.Drawing.Color.Transparent;
            this.bXoaCS.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.bXoaCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bXoaCS.BackgroundImage")));
            this.bXoaCS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXoaCS.ButtonText = "Xoá";
            this.bXoaCS.ButtonTextMarginLeft = 15;
            this.bXoaCS.ColorContrastOnClick = 45;
            this.bXoaCS.ColorContrastOnHover = 45;
            this.bXoaCS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bXoaCS.CustomizableEdges = borderEdges5;
            this.bXoaCS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bXoaCS.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bXoaCS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bXoaCS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bXoaCS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bXoaCS.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.bXoaCS.ForeColor = System.Drawing.Color.White;
            this.bXoaCS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bXoaCS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bXoaCS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bXoaCS.IconMarginLeft = 11;
            this.bXoaCS.IconPadding = 10;
            this.bXoaCS.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bXoaCS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bXoaCS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bXoaCS.IconSize = 25;
            this.bXoaCS.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.bXoaCS.IdleBorderRadius = 5;
            this.bXoaCS.IdleBorderThickness = 1;
            this.bXoaCS.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.bXoaCS.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bXoaCS.IdleIconLeftImage")));
            this.bXoaCS.IdleIconRightImage = null;
            this.bXoaCS.IndicateFocus = false;
            this.bXoaCS.Location = new System.Drawing.Point(267, 271);
            this.bXoaCS.Name = "bXoaCS";
            this.bXoaCS.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.bXoaCS.OnDisabledState.BorderRadius = 5;
            this.bXoaCS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXoaCS.OnDisabledState.BorderThickness = 1;
            this.bXoaCS.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bXoaCS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bXoaCS.OnDisabledState.IconLeftImage = null;
            this.bXoaCS.OnDisabledState.IconRightImage = null;
            this.bXoaCS.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(156)))), ((int)(((byte)(154)))));
            this.bXoaCS.onHoverState.BorderRadius = 5;
            this.bXoaCS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXoaCS.onHoverState.BorderThickness = 1;
            this.bXoaCS.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(156)))), ((int)(((byte)(154)))));
            this.bXoaCS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bXoaCS.onHoverState.IconLeftImage = null;
            this.bXoaCS.onHoverState.IconRightImage = null;
            this.bXoaCS.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.bXoaCS.OnIdleState.BorderRadius = 5;
            this.bXoaCS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXoaCS.OnIdleState.BorderThickness = 1;
            this.bXoaCS.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(75)))), ((int)(((byte)(72)))));
            this.bXoaCS.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bXoaCS.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnXoaNV.OnIdleState.IconLeftImage")));
            this.bXoaCS.OnIdleState.IconRightImage = null;
            this.bXoaCS.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(117)))), ((int)(((byte)(41)))), ((int)(((byte)(39)))));
            this.bXoaCS.OnPressedState.BorderRadius = 5;
            this.bXoaCS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXoaCS.OnPressedState.BorderThickness = 1;
            this.bXoaCS.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(117)))), ((int)(((byte)(41)))), ((int)(((byte)(39)))));
            this.bXoaCS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bXoaCS.OnPressedState.IconLeftImage = null;
            this.bXoaCS.OnPressedState.IconRightImage = null;
            this.bXoaCS.Size = new System.Drawing.Size(110, 45);
            this.bXoaCS.TabIndex = 26;
            this.bXoaCS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bXoaCS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bXoaCS.TextMarginLeft = 15;
            this.bXoaCS.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bXoaCS.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel3.Location = new System.Drawing.Point(27, 89);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(159, 23);
            this.bunifuLabel3.TabIndex = 7;
            this.bunifuLabel3.Text = "Mô tả giảng đường";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbMaGiangDuongCS
            // 
            this.tbMaGiangDuongCS.AcceptsReturn = false;
            this.tbMaGiangDuongCS.AcceptsTab = false;
            this.tbMaGiangDuongCS.AnimationSpeed = 200;
            this.tbMaGiangDuongCS.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbMaGiangDuongCS.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbMaGiangDuongCS.BackColor = System.Drawing.Color.Transparent;
            this.tbMaGiangDuongCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbMaGiangDuongCS.BackgroundImage")));
            this.tbMaGiangDuongCS.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbMaGiangDuongCS.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbMaGiangDuongCS.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbMaGiangDuongCS.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbMaGiangDuongCS.BorderRadius = 1;
            this.tbMaGiangDuongCS.BorderThickness = 1;
            this.tbMaGiangDuongCS.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbMaGiangDuongCS.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaGiangDuongCS.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbMaGiangDuongCS.DefaultText = "";
            this.tbMaGiangDuongCS.FillColor = System.Drawing.Color.White;
            this.tbMaGiangDuongCS.HideSelection = true;
            this.tbMaGiangDuongCS.IconLeft = null;
            this.tbMaGiangDuongCS.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaGiangDuongCS.IconPadding = 10;
            this.tbMaGiangDuongCS.IconRight = null;
            this.tbMaGiangDuongCS.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaGiangDuongCS.Lines = new string[0];
            this.tbMaGiangDuongCS.Location = new System.Drawing.Point(165, 34);
            this.tbMaGiangDuongCS.MaxLength = 32767;
            this.tbMaGiangDuongCS.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbMaGiangDuongCS.Modified = false;
            this.tbMaGiangDuongCS.Multiline = false;
            this.tbMaGiangDuongCS.Name = "tbMaGiangDuongCS";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaGiangDuongCS.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbMaGiangDuongCS.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaGiangDuongCS.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaGiangDuongCS.OnIdleState = stateProperties4;
            this.tbMaGiangDuongCS.Padding = new System.Windows.Forms.Padding(3);
            this.tbMaGiangDuongCS.PasswordChar = '\0';
            this.tbMaGiangDuongCS.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbMaGiangDuongCS.PlaceholderText = "Enter text";
            this.tbMaGiangDuongCS.ReadOnly = false;
            this.tbMaGiangDuongCS.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbMaGiangDuongCS.SelectedText = "";
            this.tbMaGiangDuongCS.SelectionLength = 0;
            this.tbMaGiangDuongCS.SelectionStart = 0;
            this.tbMaGiangDuongCS.ShortcutsEnabled = true;
            this.tbMaGiangDuongCS.Size = new System.Drawing.Size(240, 41);
            this.tbMaGiangDuongCS.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbMaGiangDuongCS.TabIndex = 4;
            this.tbMaGiangDuongCS.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbMaGiangDuongCS.TextMarginBottom = 0;
            this.tbMaGiangDuongCS.TextMarginLeft = 3;
            this.tbMaGiangDuongCS.TextMarginTop = 0;
            this.tbMaGiangDuongCS.TextPlaceholder = "Enter text";
            this.tbMaGiangDuongCS.UseSystemPasswordChar = false;
            this.tbMaGiangDuongCS.WordWrap = true;
            // 
            // tbMoTaGiangDuongCS
            // 
            this.tbMoTaGiangDuongCS.AcceptsReturn = false;
            this.tbMoTaGiangDuongCS.AcceptsTab = false;
            this.tbMoTaGiangDuongCS.AnimationSpeed = 200;
            this.tbMoTaGiangDuongCS.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbMoTaGiangDuongCS.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbMoTaGiangDuongCS.BackColor = System.Drawing.Color.Transparent;
            this.tbMoTaGiangDuongCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbMoTaGiangDuongCS.BackgroundImage")));
            this.tbMoTaGiangDuongCS.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbMoTaGiangDuongCS.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbMoTaGiangDuongCS.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbMoTaGiangDuongCS.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbMoTaGiangDuongCS.BorderRadius = 1;
            this.tbMoTaGiangDuongCS.BorderThickness = 1;
            this.tbMoTaGiangDuongCS.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbMoTaGiangDuongCS.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMoTaGiangDuongCS.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbMoTaGiangDuongCS.DefaultText = "";
            this.tbMoTaGiangDuongCS.FillColor = System.Drawing.Color.White;
            this.tbMoTaGiangDuongCS.HideSelection = true;
            this.tbMoTaGiangDuongCS.IconLeft = null;
            this.tbMoTaGiangDuongCS.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMoTaGiangDuongCS.IconPadding = 10;
            this.tbMoTaGiangDuongCS.IconRight = null;
            this.tbMoTaGiangDuongCS.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMoTaGiangDuongCS.Lines = new string[0];
            this.tbMoTaGiangDuongCS.Location = new System.Drawing.Point(165, 84);
            this.tbMoTaGiangDuongCS.MaxLength = 32767;
            this.tbMoTaGiangDuongCS.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbMoTaGiangDuongCS.Modified = false;
            this.tbMoTaGiangDuongCS.Multiline = false;
            this.tbMoTaGiangDuongCS.Name = "tbMoTaGiangDuongCS";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMoTaGiangDuongCS.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbMoTaGiangDuongCS.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMoTaGiangDuongCS.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMoTaGiangDuongCS.OnIdleState = stateProperties8;
            this.tbMoTaGiangDuongCS.Padding = new System.Windows.Forms.Padding(3);
            this.tbMoTaGiangDuongCS.PasswordChar = '\0';
            this.tbMoTaGiangDuongCS.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbMoTaGiangDuongCS.PlaceholderText = "Enter text";
            this.tbMoTaGiangDuongCS.ReadOnly = false;
            this.tbMoTaGiangDuongCS.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbMoTaGiangDuongCS.SelectedText = "";
            this.tbMoTaGiangDuongCS.SelectionLength = 0;
            this.tbMoTaGiangDuongCS.SelectionStart = 0;
            this.tbMoTaGiangDuongCS.ShortcutsEnabled = true;
            this.tbMoTaGiangDuongCS.Size = new System.Drawing.Size(240, 41);
            this.tbMoTaGiangDuongCS.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbMoTaGiangDuongCS.TabIndex = 6;
            this.tbMoTaGiangDuongCS.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbMoTaGiangDuongCS.TextMarginBottom = 0;
            this.tbMoTaGiangDuongCS.TextMarginLeft = 3;
            this.tbMoTaGiangDuongCS.TextMarginTop = 0;
            this.tbMoTaGiangDuongCS.TextPlaceholder = "Enter text";
            this.tbMoTaGiangDuongCS.UseSystemPasswordChar = false;
            this.tbMoTaGiangDuongCS.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel4.Location = new System.Drawing.Point(35, 43);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(137, 23);
            this.bunifuLabel4.TabIndex = 5;
            this.bunifuLabel4.Text = "Mã giảng đường";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BackColor = System.Drawing.Color.White;
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel2);
            this.bunifuGroupBox1.Controls.Add(this.tbMoTaGiangDuongTK);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel1);
            this.bunifuGroupBox1.Controls.Add(this.tbMaGiangDuongTK);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(3, 3);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(600, 125);
            this.bunifuGroupBox1.TabIndex = 4;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Tìm kiếm";
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel2.Location = new System.Drawing.Point(36, 84);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(159, 23);
            this.bunifuLabel2.TabIndex = 3;
            this.bunifuLabel2.Text = "Mô tả giảng đường";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbMoTaGiangDuongTK
            // 
            this.tbMoTaGiangDuongTK.AcceptsReturn = false;
            this.tbMoTaGiangDuongTK.AcceptsTab = false;
            this.tbMoTaGiangDuongTK.AnimationSpeed = 200;
            this.tbMoTaGiangDuongTK.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbMoTaGiangDuongTK.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbMoTaGiangDuongTK.BackColor = System.Drawing.Color.Transparent;
            this.tbMoTaGiangDuongTK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbMoTaGiangDuongTK.BackgroundImage")));
            this.tbMoTaGiangDuongTK.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbMoTaGiangDuongTK.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbMoTaGiangDuongTK.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbMoTaGiangDuongTK.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbMoTaGiangDuongTK.BorderRadius = 1;
            this.tbMoTaGiangDuongTK.BorderThickness = 1;
            this.tbMoTaGiangDuongTK.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbMoTaGiangDuongTK.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMoTaGiangDuongTK.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbMoTaGiangDuongTK.DefaultText = "";
            this.tbMoTaGiangDuongTK.FillColor = System.Drawing.Color.White;
            this.tbMoTaGiangDuongTK.HideSelection = true;
            this.tbMoTaGiangDuongTK.IconLeft = null;
            this.tbMoTaGiangDuongTK.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMoTaGiangDuongTK.IconPadding = 10;
            this.tbMoTaGiangDuongTK.IconRight = null;
            this.tbMoTaGiangDuongTK.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMoTaGiangDuongTK.Lines = new string[0];
            this.tbMoTaGiangDuongTK.Location = new System.Drawing.Point(197, 71);
            this.tbMoTaGiangDuongTK.MaxLength = 32767;
            this.tbMoTaGiangDuongTK.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbMoTaGiangDuongTK.Modified = false;
            this.tbMoTaGiangDuongTK.Multiline = false;
            this.tbMoTaGiangDuongTK.Name = "tbMoTaGiangDuongTK";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMoTaGiangDuongTK.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbMoTaGiangDuongTK.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMoTaGiangDuongTK.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMoTaGiangDuongTK.OnIdleState = stateProperties12;
            this.tbMoTaGiangDuongTK.Padding = new System.Windows.Forms.Padding(3);
            this.tbMoTaGiangDuongTK.PasswordChar = '\0';
            this.tbMoTaGiangDuongTK.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbMoTaGiangDuongTK.PlaceholderText = "Enter text";
            this.tbMoTaGiangDuongTK.ReadOnly = false;
            this.tbMoTaGiangDuongTK.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbMoTaGiangDuongTK.SelectedText = "";
            this.tbMoTaGiangDuongTK.SelectionLength = 0;
            this.tbMoTaGiangDuongTK.SelectionStart = 0;
            this.tbMoTaGiangDuongTK.ShortcutsEnabled = true;
            this.tbMoTaGiangDuongTK.Size = new System.Drawing.Size(300, 41);
            this.tbMoTaGiangDuongTK.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbMoTaGiangDuongTK.TabIndex = 2;
            this.tbMoTaGiangDuongTK.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbMoTaGiangDuongTK.TextMarginBottom = 0;
            this.tbMoTaGiangDuongTK.TextMarginLeft = 3;
            this.tbMoTaGiangDuongTK.TextMarginTop = 0;
            this.tbMoTaGiangDuongTK.TextPlaceholder = "Enter text";
            this.tbMoTaGiangDuongTK.UseSystemPasswordChar = false;
            this.tbMoTaGiangDuongTK.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel1.Location = new System.Drawing.Point(36, 34);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(137, 23);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Mã giảng đường";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbMaGiangDuongTK
            // 
            this.tbMaGiangDuongTK.AcceptsReturn = false;
            this.tbMaGiangDuongTK.AcceptsTab = false;
            this.tbMaGiangDuongTK.AnimationSpeed = 200;
            this.tbMaGiangDuongTK.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbMaGiangDuongTK.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbMaGiangDuongTK.BackColor = System.Drawing.Color.Transparent;
            this.tbMaGiangDuongTK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbMaGiangDuongTK.BackgroundImage")));
            this.tbMaGiangDuongTK.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbMaGiangDuongTK.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbMaGiangDuongTK.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbMaGiangDuongTK.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbMaGiangDuongTK.BorderRadius = 1;
            this.tbMaGiangDuongTK.BorderThickness = 1;
            this.tbMaGiangDuongTK.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbMaGiangDuongTK.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaGiangDuongTK.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbMaGiangDuongTK.DefaultText = "";
            this.tbMaGiangDuongTK.FillColor = System.Drawing.Color.White;
            this.tbMaGiangDuongTK.HideSelection = true;
            this.tbMaGiangDuongTK.IconLeft = null;
            this.tbMaGiangDuongTK.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaGiangDuongTK.IconPadding = 10;
            this.tbMaGiangDuongTK.IconRight = null;
            this.tbMaGiangDuongTK.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaGiangDuongTK.Lines = new string[0];
            this.tbMaGiangDuongTK.Location = new System.Drawing.Point(197, 25);
            this.tbMaGiangDuongTK.MaxLength = 32767;
            this.tbMaGiangDuongTK.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbMaGiangDuongTK.Modified = false;
            this.tbMaGiangDuongTK.Multiline = false;
            this.tbMaGiangDuongTK.Name = "tbMaGiangDuongTK";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaGiangDuongTK.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbMaGiangDuongTK.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaGiangDuongTK.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaGiangDuongTK.OnIdleState = stateProperties16;
            this.tbMaGiangDuongTK.Padding = new System.Windows.Forms.Padding(3);
            this.tbMaGiangDuongTK.PasswordChar = '\0';
            this.tbMaGiangDuongTK.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbMaGiangDuongTK.PlaceholderText = "Enter text";
            this.tbMaGiangDuongTK.ReadOnly = false;
            this.tbMaGiangDuongTK.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbMaGiangDuongTK.SelectedText = "";
            this.tbMaGiangDuongTK.SelectionLength = 0;
            this.tbMaGiangDuongTK.SelectionStart = 0;
            this.tbMaGiangDuongTK.ShortcutsEnabled = true;
            this.tbMaGiangDuongTK.Size = new System.Drawing.Size(300, 41);
            this.tbMaGiangDuongTK.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbMaGiangDuongTK.TabIndex = 0;
            this.tbMaGiangDuongTK.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbMaGiangDuongTK.TextMarginBottom = 0;
            this.tbMaGiangDuongTK.TextMarginLeft = 3;
            this.tbMaGiangDuongTK.TextMarginTop = 0;
            this.tbMaGiangDuongTK.TextPlaceholder = "Enter text";
            this.tbMaGiangDuongTK.UseSystemPasswordChar = false;
            this.tbMaGiangDuongTK.WordWrap = true;
            // 
            // UCGiangDuong
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.dgvGiangDuong);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Name = "UCGiangDuong";
            this.Size = new System.Drawing.Size(1030, 580);
            ((System.ComponentModel.ISupportInitialize)(this.dgvGiangDuong)).EndInit();
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox2.PerformLayout();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView dgvGiangDuong;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bHuyCS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bLuuCS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bSuaCS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bThemCS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bXoaCS;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox tbMaGiangDuongCS;
        private Bunifu.UI.WinForms.BunifuTextBox tbMoTaGiangDuongCS;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox tbMoTaGiangDuongTK;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox tbMaGiangDuongTK;
    }
}
