
namespace MTAStudentManagementSystem.GUI.UserControl
{
    partial class UcNhapDiem
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UcNhapDiem));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.dgvPhieuDiem = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.gbChinhSua = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbDiemThiCS = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbDiemThuongXuyenCS = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bHuyCS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bLuuCS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bSuaCS = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbMaPhieuDiemCS = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbDiemChuyenCanCS = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbMaHocPhanTK = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tbMaSinhVienTK = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhieuDiem)).BeginInit();
            this.gbChinhSua.SuspendLayout();
            this.bunifuGroupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // dgvPhieuDiem
            // 
            this.dgvPhieuDiem.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgvPhieuDiem.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvPhieuDiem.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPhieuDiem.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvPhieuDiem.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvPhieuDiem.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvPhieuDiem.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvPhieuDiem.ColumnHeadersHeight = 40;
            this.dgvPhieuDiem.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvPhieuDiem.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvPhieuDiem.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvPhieuDiem.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvPhieuDiem.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvPhieuDiem.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvPhieuDiem.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvPhieuDiem.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvPhieuDiem.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvPhieuDiem.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvPhieuDiem.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvPhieuDiem.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvPhieuDiem.CurrentTheme.Name = null;
            this.dgvPhieuDiem.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvPhieuDiem.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvPhieuDiem.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvPhieuDiem.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvPhieuDiem.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvPhieuDiem.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvPhieuDiem.EnableHeadersVisualStyles = false;
            this.dgvPhieuDiem.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvPhieuDiem.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvPhieuDiem.HeaderForeColor = System.Drawing.Color.White;
            this.dgvPhieuDiem.Location = new System.Drawing.Point(3, 134);
            this.dgvPhieuDiem.Name = "dgvPhieuDiem";
            this.dgvPhieuDiem.RowHeadersVisible = false;
            this.dgvPhieuDiem.RowHeadersWidth = 51;
            this.dgvPhieuDiem.RowTemplate.Height = 40;
            this.dgvPhieuDiem.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPhieuDiem.Size = new System.Drawing.Size(600, 443);
            this.dgvPhieuDiem.TabIndex = 9;
            this.dgvPhieuDiem.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // gbChinhSua
            // 
            this.gbChinhSua.BackColor = System.Drawing.Color.White;
            this.gbChinhSua.BorderColor = System.Drawing.Color.LightGray;
            this.gbChinhSua.BorderRadius = 1;
            this.gbChinhSua.BorderThickness = 1;
            this.gbChinhSua.Controls.Add(this.bunifuLabel5);
            this.gbChinhSua.Controls.Add(this.tbDiemThiCS);
            this.gbChinhSua.Controls.Add(this.bunifuLabel2);
            this.gbChinhSua.Controls.Add(this.tbDiemThuongXuyenCS);
            this.gbChinhSua.Controls.Add(this.bHuyCS);
            this.gbChinhSua.Controls.Add(this.bLuuCS);
            this.gbChinhSua.Controls.Add(this.bSuaCS);
            this.gbChinhSua.Controls.Add(this.bunifuLabel3);
            this.gbChinhSua.Controls.Add(this.tbMaPhieuDiemCS);
            this.gbChinhSua.Controls.Add(this.tbDiemChuyenCanCS);
            this.gbChinhSua.Controls.Add(this.bunifuLabel4);
            this.gbChinhSua.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.gbChinhSua.ForeColor = System.Drawing.Color.DodgerBlue;
            this.gbChinhSua.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.gbChinhSua.LabelIndent = 10;
            this.gbChinhSua.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.gbChinhSua.Location = new System.Drawing.Point(609, 3);
            this.gbChinhSua.Name = "gbChinhSua";
            this.gbChinhSua.Size = new System.Drawing.Size(418, 574);
            this.gbChinhSua.TabIndex = 8;
            this.gbChinhSua.TabStop = false;
            this.gbChinhSua.Text = "Chỉnh sửa";
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel5.Location = new System.Drawing.Point(35, 187);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(72, 23);
            this.bunifuLabel5.TabIndex = 35;
            this.bunifuLabel5.Text = "Điểm thi";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbDiemThiCS
            // 
            this.tbDiemThiCS.AcceptsReturn = false;
            this.tbDiemThiCS.AcceptsTab = false;
            this.tbDiemThiCS.AnimationSpeed = 200;
            this.tbDiemThiCS.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbDiemThiCS.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbDiemThiCS.BackColor = System.Drawing.Color.Transparent;
            this.tbDiemThiCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbDiemThiCS.BackgroundImage")));
            this.tbDiemThiCS.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbDiemThiCS.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbDiemThiCS.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbDiemThiCS.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbDiemThiCS.BorderRadius = 1;
            this.tbDiemThiCS.BorderThickness = 1;
            this.tbDiemThiCS.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbDiemThiCS.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDiemThiCS.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbDiemThiCS.DefaultText = "";
            this.tbDiemThiCS.Enabled = false;
            this.tbDiemThiCS.FillColor = System.Drawing.Color.White;
            this.tbDiemThiCS.HideSelection = true;
            this.tbDiemThiCS.IconLeft = null;
            this.tbDiemThiCS.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDiemThiCS.IconPadding = 10;
            this.tbDiemThiCS.IconRight = null;
            this.tbDiemThiCS.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDiemThiCS.Lines = new string[0];
            this.tbDiemThiCS.Location = new System.Drawing.Point(151, 178);
            this.tbDiemThiCS.MaxLength = 32767;
            this.tbDiemThiCS.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbDiemThiCS.Modified = false;
            this.tbDiemThiCS.Multiline = false;
            this.tbDiemThiCS.Name = "tbDiemThiCS";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDiemThiCS.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbDiemThiCS.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDiemThiCS.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDiemThiCS.OnIdleState = stateProperties4;
            this.tbDiemThiCS.Padding = new System.Windows.Forms.Padding(3);
            this.tbDiemThiCS.PasswordChar = '\0';
            this.tbDiemThiCS.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbDiemThiCS.PlaceholderText = "Enter text";
            this.tbDiemThiCS.ReadOnly = false;
            this.tbDiemThiCS.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbDiemThiCS.SelectedText = "";
            this.tbDiemThiCS.SelectionLength = 0;
            this.tbDiemThiCS.SelectionStart = 0;
            this.tbDiemThiCS.ShortcutsEnabled = true;
            this.tbDiemThiCS.Size = new System.Drawing.Size(240, 41);
            this.tbDiemThiCS.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbDiemThiCS.TabIndex = 34;
            this.tbDiemThiCS.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbDiemThiCS.TextMarginBottom = 0;
            this.tbDiemThiCS.TextMarginLeft = 3;
            this.tbDiemThiCS.TextMarginTop = 0;
            this.tbDiemThiCS.TextPlaceholder = "Enter text";
            this.tbDiemThiCS.UseSystemPasswordChar = false;
            this.tbDiemThiCS.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel2.Location = new System.Drawing.Point(35, 140);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(169, 23);
            this.bunifuLabel2.TabIndex = 33;
            this.bunifuLabel2.Text = "Điểm thường xuyên";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbDiemThuongXuyenCS
            // 
            this.tbDiemThuongXuyenCS.AcceptsReturn = false;
            this.tbDiemThuongXuyenCS.AcceptsTab = false;
            this.tbDiemThuongXuyenCS.AnimationSpeed = 200;
            this.tbDiemThuongXuyenCS.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbDiemThuongXuyenCS.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbDiemThuongXuyenCS.BackColor = System.Drawing.Color.Transparent;
            this.tbDiemThuongXuyenCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbDiemThuongXuyenCS.BackgroundImage")));
            this.tbDiemThuongXuyenCS.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbDiemThuongXuyenCS.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbDiemThuongXuyenCS.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbDiemThuongXuyenCS.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbDiemThuongXuyenCS.BorderRadius = 1;
            this.tbDiemThuongXuyenCS.BorderThickness = 1;
            this.tbDiemThuongXuyenCS.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbDiemThuongXuyenCS.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDiemThuongXuyenCS.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbDiemThuongXuyenCS.DefaultText = "";
            this.tbDiemThuongXuyenCS.Enabled = false;
            this.tbDiemThuongXuyenCS.FillColor = System.Drawing.Color.White;
            this.tbDiemThuongXuyenCS.HideSelection = true;
            this.tbDiemThuongXuyenCS.IconLeft = null;
            this.tbDiemThuongXuyenCS.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDiemThuongXuyenCS.IconPadding = 10;
            this.tbDiemThuongXuyenCS.IconRight = null;
            this.tbDiemThuongXuyenCS.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDiemThuongXuyenCS.Lines = new string[0];
            this.tbDiemThuongXuyenCS.Location = new System.Drawing.Point(151, 131);
            this.tbDiemThuongXuyenCS.MaxLength = 32767;
            this.tbDiemThuongXuyenCS.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbDiemThuongXuyenCS.Modified = false;
            this.tbDiemThuongXuyenCS.Multiline = false;
            this.tbDiemThuongXuyenCS.Name = "tbDiemThuongXuyenCS";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDiemThuongXuyenCS.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbDiemThuongXuyenCS.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDiemThuongXuyenCS.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDiemThuongXuyenCS.OnIdleState = stateProperties8;
            this.tbDiemThuongXuyenCS.Padding = new System.Windows.Forms.Padding(3);
            this.tbDiemThuongXuyenCS.PasswordChar = '\0';
            this.tbDiemThuongXuyenCS.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbDiemThuongXuyenCS.PlaceholderText = "Enter text";
            this.tbDiemThuongXuyenCS.ReadOnly = false;
            this.tbDiemThuongXuyenCS.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbDiemThuongXuyenCS.SelectedText = "";
            this.tbDiemThuongXuyenCS.SelectionLength = 0;
            this.tbDiemThuongXuyenCS.SelectionStart = 0;
            this.tbDiemThuongXuyenCS.ShortcutsEnabled = true;
            this.tbDiemThuongXuyenCS.Size = new System.Drawing.Size(240, 41);
            this.tbDiemThuongXuyenCS.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbDiemThuongXuyenCS.TabIndex = 32;
            this.tbDiemThuongXuyenCS.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbDiemThuongXuyenCS.TextMarginBottom = 0;
            this.tbDiemThuongXuyenCS.TextMarginLeft = 3;
            this.tbDiemThuongXuyenCS.TextMarginTop = 0;
            this.tbDiemThuongXuyenCS.TextPlaceholder = "Enter text";
            this.tbDiemThuongXuyenCS.UseSystemPasswordChar = false;
            this.tbDiemThuongXuyenCS.WordWrap = true;
            // 
            // bHuyCS
            // 
            this.bHuyCS.AllowAnimations = true;
            this.bHuyCS.AllowMouseEffects = true;
            this.bHuyCS.AllowToggling = false;
            this.bHuyCS.AnimationSpeed = 200;
            this.bHuyCS.AutoGenerateColors = true;
            this.bHuyCS.AutoRoundBorders = false;
            this.bHuyCS.AutoSizeLeftIcon = true;
            this.bHuyCS.AutoSizeRightIcon = true;
            this.bHuyCS.BackColor = System.Drawing.Color.Transparent;
            this.bHuyCS.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bHuyCS.BackgroundImage")));
            this.bHuyCS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.ButtonText = "Huỷ";
            this.bHuyCS.ButtonTextMarginLeft = 15;
            this.bHuyCS.ColorContrastOnClick = 45;
            this.bHuyCS.ColorContrastOnHover = 45;
            this.bHuyCS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bHuyCS.CustomizableEdges = borderEdges1;
            this.bHuyCS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bHuyCS.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bHuyCS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bHuyCS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bHuyCS.Enabled = false;
            this.bHuyCS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bHuyCS.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.bHuyCS.ForeColor = System.Drawing.Color.White;
            this.bHuyCS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bHuyCS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bHuyCS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bHuyCS.IconMarginLeft = 11;
            this.bHuyCS.IconPadding = 10;
            this.bHuyCS.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bHuyCS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bHuyCS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bHuyCS.IconSize = 25;
            this.bHuyCS.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.IdleBorderRadius = 5;
            this.bHuyCS.IdleBorderThickness = 1;
            this.bHuyCS.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bHuyCS.IdleIconLeftImage")));
            this.bHuyCS.IdleIconRightImage = null;
            this.bHuyCS.IndicateFocus = false;
            this.bHuyCS.Location = new System.Drawing.Point(267, 339);
            this.bHuyCS.Name = "bHuyCS";
            this.bHuyCS.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bHuyCS.OnDisabledState.BorderRadius = 5;
            this.bHuyCS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.OnDisabledState.BorderThickness = 1;
            this.bHuyCS.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bHuyCS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bHuyCS.OnDisabledState.IconLeftImage = null;
            this.bHuyCS.OnDisabledState.IconRightImage = null;
            this.bHuyCS.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(134)))), ((int)(((byte)(147)))));
            this.bHuyCS.onHoverState.BorderRadius = 5;
            this.bHuyCS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.onHoverState.BorderThickness = 1;
            this.bHuyCS.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(134)))), ((int)(((byte)(147)))));
            this.bHuyCS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bHuyCS.onHoverState.IconLeftImage = null;
            this.bHuyCS.onHoverState.IconRightImage = null;
            this.bHuyCS.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.OnIdleState.BorderRadius = 5;
            this.bHuyCS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.OnIdleState.BorderThickness = 1;
            this.bHuyCS.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(36)))), ((int)(((byte)(60)))));
            this.bHuyCS.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bHuyCS.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bHuyCS.OnIdleState.IconLeftImage")));
            this.bHuyCS.OnIdleState.IconRightImage = null;
            this.bHuyCS.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(19)))), ((int)(((byte)(33)))));
            this.bHuyCS.OnPressedState.BorderRadius = 5;
            this.bHuyCS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHuyCS.OnPressedState.BorderThickness = 1;
            this.bHuyCS.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(19)))), ((int)(((byte)(33)))));
            this.bHuyCS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bHuyCS.OnPressedState.IconLeftImage = null;
            this.bHuyCS.OnPressedState.IconRightImage = null;
            this.bHuyCS.Size = new System.Drawing.Size(118, 45);
            this.bHuyCS.TabIndex = 30;
            this.bHuyCS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bHuyCS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bHuyCS.TextMarginLeft = 15;
            this.bHuyCS.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bHuyCS.UseDefaultRadiusAndThickness = true;
            this.bHuyCS.Click += new System.EventHandler(this.bHuyCS_Click);
            // 
            // bLuuCS
            // 
            this.bLuuCS.AllowAnimations = true;
            this.bLuuCS.AllowMouseEffects = true;
            this.bLuuCS.AllowToggling = false;
            this.bLuuCS.AnimationSpeed = 200;
            this.bLuuCS.AutoGenerateColors = true;
            this.bLuuCS.AutoRoundBorders = false;
            this.bLuuCS.AutoSizeLeftIcon = true;
            this.bLuuCS.AutoSizeRightIcon = true;
            this.bLuuCS.BackColor = System.Drawing.Color.Transparent;
            this.bLuuCS.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bLuuCS.BackgroundImage")));
            this.bLuuCS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.ButtonText = "Lưu";
            this.bLuuCS.ButtonTextMarginLeft = 15;
            this.bLuuCS.ColorContrastOnClick = 45;
            this.bLuuCS.ColorContrastOnHover = 45;
            this.bLuuCS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bLuuCS.CustomizableEdges = borderEdges2;
            this.bLuuCS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bLuuCS.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bLuuCS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bLuuCS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bLuuCS.Enabled = false;
            this.bLuuCS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bLuuCS.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.bLuuCS.ForeColor = System.Drawing.Color.White;
            this.bLuuCS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bLuuCS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bLuuCS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bLuuCS.IconMarginLeft = 11;
            this.bLuuCS.IconPadding = 10;
            this.bLuuCS.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bLuuCS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bLuuCS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bLuuCS.IconSize = 25;
            this.bLuuCS.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.IdleBorderRadius = 5;
            this.bLuuCS.IdleBorderThickness = 1;
            this.bLuuCS.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bLuuCS.IdleIconLeftImage")));
            this.bLuuCS.IdleIconRightImage = null;
            this.bLuuCS.IndicateFocus = false;
            this.bLuuCS.Location = new System.Drawing.Point(62, 339);
            this.bLuuCS.Name = "bLuuCS";
            this.bLuuCS.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bLuuCS.OnDisabledState.BorderRadius = 5;
            this.bLuuCS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.OnDisabledState.BorderThickness = 1;
            this.bLuuCS.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bLuuCS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bLuuCS.OnDisabledState.IconLeftImage = null;
            this.bLuuCS.OnDisabledState.IconRightImage = null;
            this.bLuuCS.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(152)))), ((int)(((byte)(181)))));
            this.bLuuCS.onHoverState.BorderRadius = 5;
            this.bLuuCS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.onHoverState.BorderThickness = 1;
            this.bLuuCS.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(152)))), ((int)(((byte)(181)))));
            this.bLuuCS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bLuuCS.onHoverState.IconLeftImage = null;
            this.bLuuCS.onHoverState.IconRightImage = null;
            this.bLuuCS.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.OnIdleState.BorderRadius = 5;
            this.bLuuCS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.OnIdleState.BorderThickness = 1;
            this.bLuuCS.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(195)))), ((int)(((byte)(68)))), ((int)(((byte)(122)))));
            this.bLuuCS.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bLuuCS.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bLuuCS.OnIdleState.IconLeftImage")));
            this.bLuuCS.OnIdleState.IconRightImage = null;
            this.bLuuCS.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(37)))), ((int)(((byte)(67)))));
            this.bLuuCS.OnPressedState.BorderRadius = 5;
            this.bLuuCS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLuuCS.OnPressedState.BorderThickness = 1;
            this.bLuuCS.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(37)))), ((int)(((byte)(67)))));
            this.bLuuCS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bLuuCS.OnPressedState.IconLeftImage = null;
            this.bLuuCS.OnPressedState.IconRightImage = null;
            this.bLuuCS.Size = new System.Drawing.Size(118, 45);
            this.bLuuCS.TabIndex = 31;
            this.bLuuCS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bLuuCS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bLuuCS.TextMarginLeft = 15;
            this.bLuuCS.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bLuuCS.UseDefaultRadiusAndThickness = true;
            this.bLuuCS.Click += new System.EventHandler(this.bLuuCS_Click);
            // 
            // bSuaCS
            // 
            this.bSuaCS.AllowAnimations = true;
            this.bSuaCS.AllowMouseEffects = true;
            this.bSuaCS.AllowToggling = false;
            this.bSuaCS.AnimationSpeed = 200;
            this.bSuaCS.AutoGenerateColors = true;
            this.bSuaCS.AutoRoundBorders = false;
            this.bSuaCS.AutoSizeLeftIcon = true;
            this.bSuaCS.AutoSizeRightIcon = true;
            this.bSuaCS.BackColor = System.Drawing.Color.Transparent;
            this.bSuaCS.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bSuaCS.BackgroundImage")));
            this.bSuaCS.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.ButtonText = "Sửa";
            this.bSuaCS.ButtonTextMarginLeft = 15;
            this.bSuaCS.ColorContrastOnClick = 45;
            this.bSuaCS.ColorContrastOnHover = 45;
            this.bSuaCS.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bSuaCS.CustomizableEdges = borderEdges3;
            this.bSuaCS.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bSuaCS.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bSuaCS.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bSuaCS.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bSuaCS.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bSuaCS.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold);
            this.bSuaCS.ForeColor = System.Drawing.Color.White;
            this.bSuaCS.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bSuaCS.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bSuaCS.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bSuaCS.IconMarginLeft = 11;
            this.bSuaCS.IconPadding = 10;
            this.bSuaCS.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bSuaCS.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bSuaCS.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bSuaCS.IconSize = 25;
            this.bSuaCS.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.IdleBorderRadius = 5;
            this.bSuaCS.IdleBorderThickness = 1;
            this.bSuaCS.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bSuaCS.IdleIconLeftImage")));
            this.bSuaCS.IdleIconRightImage = null;
            this.bSuaCS.IndicateFocus = false;
            this.bSuaCS.Location = new System.Drawing.Point(164, 272);
            this.bSuaCS.Name = "bSuaCS";
            this.bSuaCS.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.bSuaCS.OnDisabledState.BorderRadius = 5;
            this.bSuaCS.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.OnDisabledState.BorderThickness = 1;
            this.bSuaCS.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bSuaCS.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bSuaCS.OnDisabledState.IconLeftImage = null;
            this.bSuaCS.OnDisabledState.IconRightImage = null;
            this.bSuaCS.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(159)))), ((int)(((byte)(217)))), ((int)(((byte)(235)))));
            this.bSuaCS.onHoverState.BorderRadius = 5;
            this.bSuaCS.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.onHoverState.BorderThickness = 1;
            this.bSuaCS.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(159)))), ((int)(((byte)(217)))), ((int)(((byte)(235)))));
            this.bSuaCS.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bSuaCS.onHoverState.IconLeftImage = null;
            this.bSuaCS.onHoverState.IconRightImage = null;
            this.bSuaCS.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.OnIdleState.BorderRadius = 5;
            this.bSuaCS.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.OnIdleState.BorderThickness = 1;
            this.bSuaCS.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(187)))), ((int)(((byte)(219)))));
            this.bSuaCS.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bSuaCS.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bSuaCS.OnIdleState.IconLeftImage")));
            this.bSuaCS.OnIdleState.IconRightImage = null;
            this.bSuaCS.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(102)))), ((int)(((byte)(120)))));
            this.bSuaCS.OnPressedState.BorderRadius = 5;
            this.bSuaCS.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSuaCS.OnPressedState.BorderThickness = 1;
            this.bSuaCS.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(102)))), ((int)(((byte)(120)))));
            this.bSuaCS.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bSuaCS.OnPressedState.IconLeftImage = null;
            this.bSuaCS.OnPressedState.IconRightImage = null;
            this.bSuaCS.Size = new System.Drawing.Size(118, 45);
            this.bSuaCS.TabIndex = 27;
            this.bSuaCS.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bSuaCS.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bSuaCS.TextMarginLeft = 15;
            this.bSuaCS.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.bSuaCS.UseDefaultRadiusAndThickness = true;
            this.bSuaCS.Click += new System.EventHandler(this.bSuaCS_Click);
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel3.Location = new System.Drawing.Point(35, 93);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(145, 23);
            this.bunifuLabel3.TabIndex = 7;
            this.bunifuLabel3.Text = "Điểm chuyên cần";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbMaPhieuDiemCS
            // 
            this.tbMaPhieuDiemCS.AcceptsReturn = false;
            this.tbMaPhieuDiemCS.AcceptsTab = false;
            this.tbMaPhieuDiemCS.AnimationSpeed = 200;
            this.tbMaPhieuDiemCS.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbMaPhieuDiemCS.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbMaPhieuDiemCS.BackColor = System.Drawing.Color.Transparent;
            this.tbMaPhieuDiemCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbMaPhieuDiemCS.BackgroundImage")));
            this.tbMaPhieuDiemCS.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbMaPhieuDiemCS.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbMaPhieuDiemCS.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbMaPhieuDiemCS.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbMaPhieuDiemCS.BorderRadius = 1;
            this.tbMaPhieuDiemCS.BorderThickness = 1;
            this.tbMaPhieuDiemCS.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbMaPhieuDiemCS.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaPhieuDiemCS.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbMaPhieuDiemCS.DefaultText = "";
            this.tbMaPhieuDiemCS.Enabled = false;
            this.tbMaPhieuDiemCS.FillColor = System.Drawing.Color.White;
            this.tbMaPhieuDiemCS.HideSelection = true;
            this.tbMaPhieuDiemCS.IconLeft = null;
            this.tbMaPhieuDiemCS.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaPhieuDiemCS.IconPadding = 10;
            this.tbMaPhieuDiemCS.IconRight = null;
            this.tbMaPhieuDiemCS.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaPhieuDiemCS.Lines = new string[0];
            this.tbMaPhieuDiemCS.Location = new System.Drawing.Point(151, 34);
            this.tbMaPhieuDiemCS.MaxLength = 32767;
            this.tbMaPhieuDiemCS.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbMaPhieuDiemCS.Modified = false;
            this.tbMaPhieuDiemCS.Multiline = false;
            this.tbMaPhieuDiemCS.Name = "tbMaPhieuDiemCS";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaPhieuDiemCS.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbMaPhieuDiemCS.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaPhieuDiemCS.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaPhieuDiemCS.OnIdleState = stateProperties12;
            this.tbMaPhieuDiemCS.Padding = new System.Windows.Forms.Padding(3);
            this.tbMaPhieuDiemCS.PasswordChar = '\0';
            this.tbMaPhieuDiemCS.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbMaPhieuDiemCS.PlaceholderText = "Enter text";
            this.tbMaPhieuDiemCS.ReadOnly = false;
            this.tbMaPhieuDiemCS.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbMaPhieuDiemCS.SelectedText = "";
            this.tbMaPhieuDiemCS.SelectionLength = 0;
            this.tbMaPhieuDiemCS.SelectionStart = 0;
            this.tbMaPhieuDiemCS.ShortcutsEnabled = true;
            this.tbMaPhieuDiemCS.Size = new System.Drawing.Size(240, 41);
            this.tbMaPhieuDiemCS.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbMaPhieuDiemCS.TabIndex = 4;
            this.tbMaPhieuDiemCS.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbMaPhieuDiemCS.TextMarginBottom = 0;
            this.tbMaPhieuDiemCS.TextMarginLeft = 3;
            this.tbMaPhieuDiemCS.TextMarginTop = 0;
            this.tbMaPhieuDiemCS.TextPlaceholder = "Enter text";
            this.tbMaPhieuDiemCS.UseSystemPasswordChar = false;
            this.tbMaPhieuDiemCS.WordWrap = true;
            // 
            // tbDiemChuyenCanCS
            // 
            this.tbDiemChuyenCanCS.AcceptsReturn = false;
            this.tbDiemChuyenCanCS.AcceptsTab = false;
            this.tbDiemChuyenCanCS.AnimationSpeed = 200;
            this.tbDiemChuyenCanCS.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbDiemChuyenCanCS.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbDiemChuyenCanCS.BackColor = System.Drawing.Color.Transparent;
            this.tbDiemChuyenCanCS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbDiemChuyenCanCS.BackgroundImage")));
            this.tbDiemChuyenCanCS.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbDiemChuyenCanCS.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbDiemChuyenCanCS.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbDiemChuyenCanCS.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbDiemChuyenCanCS.BorderRadius = 1;
            this.tbDiemChuyenCanCS.BorderThickness = 1;
            this.tbDiemChuyenCanCS.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbDiemChuyenCanCS.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDiemChuyenCanCS.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbDiemChuyenCanCS.DefaultText = "";
            this.tbDiemChuyenCanCS.Enabled = false;
            this.tbDiemChuyenCanCS.FillColor = System.Drawing.Color.White;
            this.tbDiemChuyenCanCS.HideSelection = true;
            this.tbDiemChuyenCanCS.IconLeft = null;
            this.tbDiemChuyenCanCS.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDiemChuyenCanCS.IconPadding = 10;
            this.tbDiemChuyenCanCS.IconRight = null;
            this.tbDiemChuyenCanCS.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbDiemChuyenCanCS.Lines = new string[0];
            this.tbDiemChuyenCanCS.Location = new System.Drawing.Point(151, 84);
            this.tbDiemChuyenCanCS.MaxLength = 32767;
            this.tbDiemChuyenCanCS.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbDiemChuyenCanCS.Modified = false;
            this.tbDiemChuyenCanCS.Multiline = false;
            this.tbDiemChuyenCanCS.Name = "tbDiemChuyenCanCS";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDiemChuyenCanCS.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbDiemChuyenCanCS.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDiemChuyenCanCS.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbDiemChuyenCanCS.OnIdleState = stateProperties16;
            this.tbDiemChuyenCanCS.Padding = new System.Windows.Forms.Padding(3);
            this.tbDiemChuyenCanCS.PasswordChar = '\0';
            this.tbDiemChuyenCanCS.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbDiemChuyenCanCS.PlaceholderText = "Enter text";
            this.tbDiemChuyenCanCS.ReadOnly = false;
            this.tbDiemChuyenCanCS.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbDiemChuyenCanCS.SelectedText = "";
            this.tbDiemChuyenCanCS.SelectionLength = 0;
            this.tbDiemChuyenCanCS.SelectionStart = 0;
            this.tbDiemChuyenCanCS.ShortcutsEnabled = true;
            this.tbDiemChuyenCanCS.Size = new System.Drawing.Size(240, 41);
            this.tbDiemChuyenCanCS.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbDiemChuyenCanCS.TabIndex = 6;
            this.tbDiemChuyenCanCS.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbDiemChuyenCanCS.TextMarginBottom = 0;
            this.tbDiemChuyenCanCS.TextMarginLeft = 3;
            this.tbDiemChuyenCanCS.TextMarginTop = 0;
            this.tbDiemChuyenCanCS.TextPlaceholder = "Enter text";
            this.tbDiemChuyenCanCS.UseSystemPasswordChar = false;
            this.tbDiemChuyenCanCS.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel4.Location = new System.Drawing.Point(40, 43);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(125, 23);
            this.bunifuLabel4.TabIndex = 5;
            this.bunifuLabel4.Text = "Mã phiếu điểm";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BackColor = System.Drawing.Color.White;
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 1;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel6);
            this.bunifuGroupBox1.Controls.Add(this.tbMaHocPhanTK);
            this.bunifuGroupBox1.Controls.Add(this.bunifuLabel1);
            this.bunifuGroupBox1.Controls.Add(this.tbMaSinhVienTK);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(3, 3);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(600, 125);
            this.bunifuGroupBox1.TabIndex = 7;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Tìm kiếm";
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel6.Location = new System.Drawing.Point(66, 81);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(108, 23);
            this.bunifuLabel6.TabIndex = 3;
            this.bunifuLabel6.Text = "Mã học phần";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbMaHocPhanTK
            // 
            this.tbMaHocPhanTK.AcceptsReturn = false;
            this.tbMaHocPhanTK.AcceptsTab = false;
            this.tbMaHocPhanTK.AnimationSpeed = 200;
            this.tbMaHocPhanTK.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbMaHocPhanTK.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbMaHocPhanTK.BackColor = System.Drawing.Color.Transparent;
            this.tbMaHocPhanTK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbMaHocPhanTK.BackgroundImage")));
            this.tbMaHocPhanTK.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbMaHocPhanTK.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbMaHocPhanTK.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbMaHocPhanTK.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbMaHocPhanTK.BorderRadius = 1;
            this.tbMaHocPhanTK.BorderThickness = 1;
            this.tbMaHocPhanTK.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbMaHocPhanTK.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaHocPhanTK.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbMaHocPhanTK.DefaultText = "";
            this.tbMaHocPhanTK.FillColor = System.Drawing.Color.White;
            this.tbMaHocPhanTK.HideSelection = true;
            this.tbMaHocPhanTK.IconLeft = null;
            this.tbMaHocPhanTK.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaHocPhanTK.IconPadding = 10;
            this.tbMaHocPhanTK.IconRight = null;
            this.tbMaHocPhanTK.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaHocPhanTK.Lines = new string[0];
            this.tbMaHocPhanTK.Location = new System.Drawing.Point(197, 72);
            this.tbMaHocPhanTK.MaxLength = 32767;
            this.tbMaHocPhanTK.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbMaHocPhanTK.Modified = false;
            this.tbMaHocPhanTK.Multiline = false;
            this.tbMaHocPhanTK.Name = "tbMaHocPhanTK";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaHocPhanTK.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbMaHocPhanTK.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaHocPhanTK.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaHocPhanTK.OnIdleState = stateProperties20;
            this.tbMaHocPhanTK.Padding = new System.Windows.Forms.Padding(3);
            this.tbMaHocPhanTK.PasswordChar = '\0';
            this.tbMaHocPhanTK.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbMaHocPhanTK.PlaceholderText = "Enter text";
            this.tbMaHocPhanTK.ReadOnly = false;
            this.tbMaHocPhanTK.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbMaHocPhanTK.SelectedText = "";
            this.tbMaHocPhanTK.SelectionLength = 0;
            this.tbMaHocPhanTK.SelectionStart = 0;
            this.tbMaHocPhanTK.ShortcutsEnabled = true;
            this.tbMaHocPhanTK.Size = new System.Drawing.Size(300, 41);
            this.tbMaHocPhanTK.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbMaHocPhanTK.TabIndex = 2;
            this.tbMaHocPhanTK.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbMaHocPhanTK.TextMarginBottom = 0;
            this.tbMaHocPhanTK.TextMarginLeft = 3;
            this.tbMaHocPhanTK.TextMarginTop = 0;
            this.tbMaHocPhanTK.TextPlaceholder = "Enter text";
            this.tbMaHocPhanTK.UseSystemPasswordChar = false;
            this.tbMaHocPhanTK.WordWrap = true;
            this.tbMaHocPhanTK.TextChange += new System.EventHandler(this.tbMaHocPhanTK_TextChange);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Open Sans", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuLabel1.Location = new System.Drawing.Point(66, 34);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(105, 23);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Mã sinh viên";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tbMaSinhVienTK
            // 
            this.tbMaSinhVienTK.AcceptsReturn = false;
            this.tbMaSinhVienTK.AcceptsTab = false;
            this.tbMaSinhVienTK.AnimationSpeed = 200;
            this.tbMaSinhVienTK.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbMaSinhVienTK.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbMaSinhVienTK.BackColor = System.Drawing.Color.Transparent;
            this.tbMaSinhVienTK.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbMaSinhVienTK.BackgroundImage")));
            this.tbMaSinhVienTK.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbMaSinhVienTK.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbMaSinhVienTK.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbMaSinhVienTK.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbMaSinhVienTK.BorderRadius = 1;
            this.tbMaSinhVienTK.BorderThickness = 1;
            this.tbMaSinhVienTK.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbMaSinhVienTK.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaSinhVienTK.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tbMaSinhVienTK.DefaultText = "";
            this.tbMaSinhVienTK.FillColor = System.Drawing.Color.White;
            this.tbMaSinhVienTK.HideSelection = true;
            this.tbMaSinhVienTK.IconLeft = null;
            this.tbMaSinhVienTK.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaSinhVienTK.IconPadding = 10;
            this.tbMaSinhVienTK.IconRight = null;
            this.tbMaSinhVienTK.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbMaSinhVienTK.Lines = new string[0];
            this.tbMaSinhVienTK.Location = new System.Drawing.Point(197, 25);
            this.tbMaSinhVienTK.MaxLength = 32767;
            this.tbMaSinhVienTK.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbMaSinhVienTK.Modified = false;
            this.tbMaSinhVienTK.Multiline = false;
            this.tbMaSinhVienTK.Name = "tbMaSinhVienTK";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaSinhVienTK.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbMaSinhVienTK.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaSinhVienTK.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbMaSinhVienTK.OnIdleState = stateProperties24;
            this.tbMaSinhVienTK.Padding = new System.Windows.Forms.Padding(3);
            this.tbMaSinhVienTK.PasswordChar = '\0';
            this.tbMaSinhVienTK.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbMaSinhVienTK.PlaceholderText = "Enter text";
            this.tbMaSinhVienTK.ReadOnly = false;
            this.tbMaSinhVienTK.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbMaSinhVienTK.SelectedText = "";
            this.tbMaSinhVienTK.SelectionLength = 0;
            this.tbMaSinhVienTK.SelectionStart = 0;
            this.tbMaSinhVienTK.ShortcutsEnabled = true;
            this.tbMaSinhVienTK.Size = new System.Drawing.Size(300, 41);
            this.tbMaSinhVienTK.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbMaSinhVienTK.TabIndex = 0;
            this.tbMaSinhVienTK.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbMaSinhVienTK.TextMarginBottom = 0;
            this.tbMaSinhVienTK.TextMarginLeft = 3;
            this.tbMaSinhVienTK.TextMarginTop = 0;
            this.tbMaSinhVienTK.TextPlaceholder = "Enter text";
            this.tbMaSinhVienTK.UseSystemPasswordChar = false;
            this.tbMaSinhVienTK.WordWrap = true;
            this.tbMaSinhVienTK.TextChange += new System.EventHandler(this.tbMaSinhVienTK_TextChange);
            // 
            // UCNhapDiem
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.Controls.Add(this.dgvPhieuDiem);
            this.Controls.Add(this.gbChinhSua);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Name = "UcNhapDiem";
            this.Size = new System.Drawing.Size(1030, 580);
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhieuDiem)).EndInit();
            this.gbChinhSua.ResumeLayout(false);
            this.gbChinhSua.PerformLayout();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDataGridView dgvPhieuDiem;
        private Bunifu.UI.WinForms.BunifuGroupBox gbChinhSua;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bHuyCS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bLuuCS;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bSuaCS;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox tbMaPhieuDiemCS;
        private Bunifu.UI.WinForms.BunifuTextBox tbDiemChuyenCanCS;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox tbMaSinhVienTK;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox tbDiemThiCS;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox tbDiemThuongXuyenCS;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox tbMaHocPhanTK;
    }
}
