
namespace QuanLyDiem.GUI.Forms
{
    partial class FDashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FDashboard));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.pLeft = new Bunifu.UI.WinForms.BunifuPanel();
            this.bLop = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.sLeft = new Bunifu.UI.WinForms.BunifuSeparator();
            this.lLogo = new Bunifu.UI.WinForms.BunifuLabel();
            this.pbLogo = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.pSlider = new Bunifu.UI.WinForms.BunifuPanel();
            this.bDangXuat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bXemDiem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bBangDiem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bPhong = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bHocPhan = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bSinhVien = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bTongQuan = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pTop1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.lTop = new Bunifu.UI.WinForms.BunifuLabel();
            this.pTop2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.lTime = new Bunifu.UI.WinForms.BunifuLabel();
            this.lName = new Bunifu.UI.WinForms.BunifuLabel();
            this.lXinChao = new Bunifu.UI.WinForms.BunifuLabel();
            this.dcDashboard = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.pUserControl = new Bunifu.UI.WinForms.BunifuPanel();
            this.pLeft.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbLogo)).BeginInit();
            this.pTop1.SuspendLayout();
            this.pTop2.SuspendLayout();
            this.SuspendLayout();
            // 
            // pLeft
            // 
            this.pLeft.BackgroundColor = System.Drawing.Color.DodgerBlue;
            this.pLeft.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pLeft.BackgroundImage")));
            this.pLeft.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pLeft.BorderColor = System.Drawing.Color.DodgerBlue;
            this.pLeft.BorderRadius = 0;
            this.pLeft.BorderThickness = 0;
            this.pLeft.Controls.Add(this.bLop);
            this.pLeft.Controls.Add(this.sLeft);
            this.pLeft.Controls.Add(this.lLogo);
            this.pLeft.Controls.Add(this.pbLogo);
            this.pLeft.Controls.Add(this.pSlider);
            this.pLeft.Controls.Add(this.bDangXuat);
            this.pLeft.Controls.Add(this.bXemDiem);
            this.pLeft.Controls.Add(this.bBangDiem);
            this.pLeft.Controls.Add(this.bPhong);
            this.pLeft.Controls.Add(this.bHocPhan);
            this.pLeft.Controls.Add(this.bSinhVien);
            this.pLeft.Controls.Add(this.bTongQuan);
            this.pLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.pLeft.Location = new System.Drawing.Point(0, 0);
            this.pLeft.Name = "pLeft";
            this.pLeft.ShowBorders = false;
            this.pLeft.Size = new System.Drawing.Size(250, 720);
            this.pLeft.TabIndex = 0;
            // 
            // bLop
            // 
            this.bLop.AllowAnimations = true;
            this.bLop.AllowMouseEffects = true;
            this.bLop.AllowToggling = false;
            this.bLop.AnimationSpeed = 200;
            this.bLop.AutoGenerateColors = false;
            this.bLop.AutoRoundBorders = false;
            this.bLop.AutoSizeLeftIcon = true;
            this.bLop.AutoSizeRightIcon = true;
            this.bLop.BackColor = System.Drawing.Color.Transparent;
            this.bLop.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bLop.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bLop.BackgroundImage")));
            this.bLop.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLop.ButtonText = "Lớp";
            this.bLop.ButtonTextMarginLeft = 0;
            this.bLop.ColorContrastOnClick = 45;
            this.bLop.ColorContrastOnHover = 45;
            this.bLop.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bLop.CustomizableEdges = borderEdges1;
            this.bLop.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bLop.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bLop.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bLop.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bLop.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bLop.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.bLop.ForeColor = System.Drawing.Color.White;
            this.bLop.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bLop.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bLop.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bLop.IconMarginLeft = 11;
            this.bLop.IconPadding = 10;
            this.bLop.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bLop.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bLop.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bLop.IconSize = 25;
            this.bLop.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bLop.IdleBorderRadius = 1;
            this.bLop.IdleBorderThickness = 1;
            this.bLop.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bLop.IdleIconLeftImage = null;
            this.bLop.IdleIconRightImage = null;
            this.bLop.IndicateFocus = false;
            this.bLop.Location = new System.Drawing.Point(25, 269);
            this.bLop.Name = "bLop";
            this.bLop.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bLop.OnDisabledState.BorderRadius = 1;
            this.bLop.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLop.OnDisabledState.BorderThickness = 1;
            this.bLop.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bLop.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bLop.OnDisabledState.IconLeftImage = null;
            this.bLop.OnDisabledState.IconRightImage = null;
            this.bLop.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bLop.onHoverState.BorderRadius = 1;
            this.bLop.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLop.onHoverState.BorderThickness = 1;
            this.bLop.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bLop.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bLop.onHoverState.IconLeftImage = null;
            this.bLop.onHoverState.IconRightImage = null;
            this.bLop.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bLop.OnIdleState.BorderRadius = 1;
            this.bLop.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLop.OnIdleState.BorderThickness = 1;
            this.bLop.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bLop.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bLop.OnIdleState.IconLeftImage = null;
            this.bLop.OnIdleState.IconRightImage = null;
            this.bLop.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bLop.OnPressedState.BorderRadius = 1;
            this.bLop.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bLop.OnPressedState.BorderThickness = 1;
            this.bLop.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bLop.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bLop.OnPressedState.IconLeftImage = null;
            this.bLop.OnPressedState.IconRightImage = null;
            this.bLop.Size = new System.Drawing.Size(225, 60);
            this.bLop.TabIndex = 10;
            this.bLop.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bLop.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bLop.TextMarginLeft = 0;
            this.bLop.TextPadding = new System.Windows.Forms.Padding(0);
            this.bLop.UseDefaultRadiusAndThickness = true;
            this.bLop.Click += new System.EventHandler(this.bLop_Click);
            // 
            // sLeft
            // 
            this.sLeft.BackColor = System.Drawing.Color.Transparent;
            this.sLeft.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sLeft.BackgroundImage")));
            this.sLeft.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.sLeft.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.sLeft.LineColor = System.Drawing.Color.Silver;
            this.sLeft.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.sLeft.LineThickness = 1;
            this.sLeft.Location = new System.Drawing.Point(0, 123);
            this.sLeft.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.sLeft.Name = "sLeft";
            this.sLeft.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.sLeft.Size = new System.Drawing.Size(250, 17);
            this.sLeft.TabIndex = 2;
            // 
            // lLogo
            // 
            this.lLogo.AllowParentOverrides = false;
            this.lLogo.AutoEllipsis = false;
            this.lLogo.CursorType = null;
            this.lLogo.Font = new System.Drawing.Font("Open Sans", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lLogo.ForeColor = System.Drawing.SystemColors.Control;
            this.lLogo.Location = new System.Drawing.Point(25, 89);
            this.lLogo.Name = "lLogo";
            this.lLogo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lLogo.Size = new System.Drawing.Size(206, 27);
            this.lLogo.TabIndex = 9;
            this.lLogo.Text = "MTA Grading System";
            this.lLogo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lLogo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pbLogo
            // 
            this.pbLogo.AllowFocused = false;
            this.pbLogo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbLogo.AutoSizeHeight = true;
            this.pbLogo.BorderRadius = 40;
            this.pbLogo.Image = ((System.Drawing.Image)(resources.GetObject("pbLogo.Image")));
            this.pbLogo.IsCircle = true;
            this.pbLogo.Location = new System.Drawing.Point(84, 3);
            this.pbLogo.Name = "pbLogo";
            this.pbLogo.Size = new System.Drawing.Size(80, 80);
            this.pbLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbLogo.TabIndex = 1;
            this.pbLogo.TabStop = false;
            this.pbLogo.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // pSlider
            // 
            this.pSlider.BackgroundColor = System.Drawing.Color.Transparent;
            this.pSlider.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pSlider.BackgroundImage")));
            this.pSlider.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pSlider.BorderColor = System.Drawing.Color.Transparent;
            this.pSlider.BorderRadius = 0;
            this.pSlider.BorderThickness = 0;
            this.pSlider.Location = new System.Drawing.Point(14, 137);
            this.pSlider.Name = "pSlider";
            this.pSlider.ShowBorders = true;
            this.pSlider.Size = new System.Drawing.Size(5, 60);
            this.pSlider.TabIndex = 1;
            // 
            // bDangXuat
            // 
            this.bDangXuat.AllowAnimations = true;
            this.bDangXuat.AllowMouseEffects = true;
            this.bDangXuat.AllowToggling = false;
            this.bDangXuat.AnimationSpeed = 200;
            this.bDangXuat.AutoGenerateColors = false;
            this.bDangXuat.AutoRoundBorders = false;
            this.bDangXuat.AutoSizeLeftIcon = true;
            this.bDangXuat.AutoSizeRightIcon = true;
            this.bDangXuat.BackColor = System.Drawing.Color.Transparent;
            this.bDangXuat.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bDangXuat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bDangXuat.BackgroundImage")));
            this.bDangXuat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bDangXuat.ButtonText = "Đăng xuất";
            this.bDangXuat.ButtonTextMarginLeft = 0;
            this.bDangXuat.ColorContrastOnClick = 45;
            this.bDangXuat.ColorContrastOnHover = 45;
            this.bDangXuat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bDangXuat.CustomizableEdges = borderEdges2;
            this.bDangXuat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bDangXuat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bDangXuat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bDangXuat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bDangXuat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bDangXuat.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.bDangXuat.ForeColor = System.Drawing.Color.White;
            this.bDangXuat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bDangXuat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bDangXuat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bDangXuat.IconMarginLeft = 11;
            this.bDangXuat.IconPadding = 10;
            this.bDangXuat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bDangXuat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bDangXuat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bDangXuat.IconSize = 25;
            this.bDangXuat.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bDangXuat.IdleBorderRadius = 1;
            this.bDangXuat.IdleBorderThickness = 1;
            this.bDangXuat.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bDangXuat.IdleIconLeftImage = null;
            this.bDangXuat.IdleIconRightImage = null;
            this.bDangXuat.IndicateFocus = false;
            this.bDangXuat.Location = new System.Drawing.Point(25, 599);
            this.bDangXuat.Name = "bDangXuat";
            this.bDangXuat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bDangXuat.OnDisabledState.BorderRadius = 1;
            this.bDangXuat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bDangXuat.OnDisabledState.BorderThickness = 1;
            this.bDangXuat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bDangXuat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bDangXuat.OnDisabledState.IconLeftImage = null;
            this.bDangXuat.OnDisabledState.IconRightImage = null;
            this.bDangXuat.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bDangXuat.onHoverState.BorderRadius = 1;
            this.bDangXuat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bDangXuat.onHoverState.BorderThickness = 1;
            this.bDangXuat.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bDangXuat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bDangXuat.onHoverState.IconLeftImage = null;
            this.bDangXuat.onHoverState.IconRightImage = null;
            this.bDangXuat.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bDangXuat.OnIdleState.BorderRadius = 1;
            this.bDangXuat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bDangXuat.OnIdleState.BorderThickness = 1;
            this.bDangXuat.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bDangXuat.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bDangXuat.OnIdleState.IconLeftImage = null;
            this.bDangXuat.OnIdleState.IconRightImage = null;
            this.bDangXuat.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bDangXuat.OnPressedState.BorderRadius = 1;
            this.bDangXuat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bDangXuat.OnPressedState.BorderThickness = 1;
            this.bDangXuat.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bDangXuat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bDangXuat.OnPressedState.IconLeftImage = null;
            this.bDangXuat.OnPressedState.IconRightImage = null;
            this.bDangXuat.Size = new System.Drawing.Size(225, 60);
            this.bDangXuat.TabIndex = 8;
            this.bDangXuat.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bDangXuat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bDangXuat.TextMarginLeft = 0;
            this.bDangXuat.TextPadding = new System.Windows.Forms.Padding(0);
            this.bDangXuat.UseDefaultRadiusAndThickness = true;
            this.bDangXuat.Click += new System.EventHandler(this.bDangXuat_Click);
            // 
            // bXemDiem
            // 
            this.bXemDiem.AllowAnimations = true;
            this.bXemDiem.AllowMouseEffects = true;
            this.bXemDiem.AllowToggling = false;
            this.bXemDiem.AnimationSpeed = 200;
            this.bXemDiem.AutoGenerateColors = false;
            this.bXemDiem.AutoRoundBorders = false;
            this.bXemDiem.AutoSizeLeftIcon = true;
            this.bXemDiem.AutoSizeRightIcon = true;
            this.bXemDiem.BackColor = System.Drawing.Color.Transparent;
            this.bXemDiem.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bXemDiem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bXemDiem.BackgroundImage")));
            this.bXemDiem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXemDiem.ButtonText = "Xem điểm";
            this.bXemDiem.ButtonTextMarginLeft = 0;
            this.bXemDiem.ColorContrastOnClick = 45;
            this.bXemDiem.ColorContrastOnHover = 45;
            this.bXemDiem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bXemDiem.CustomizableEdges = borderEdges3;
            this.bXemDiem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bXemDiem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bXemDiem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bXemDiem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bXemDiem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bXemDiem.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.bXemDiem.ForeColor = System.Drawing.Color.White;
            this.bXemDiem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bXemDiem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bXemDiem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bXemDiem.IconMarginLeft = 11;
            this.bXemDiem.IconPadding = 10;
            this.bXemDiem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bXemDiem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bXemDiem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bXemDiem.IconSize = 25;
            this.bXemDiem.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bXemDiem.IdleBorderRadius = 1;
            this.bXemDiem.IdleBorderThickness = 1;
            this.bXemDiem.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bXemDiem.IdleIconLeftImage = null;
            this.bXemDiem.IdleIconRightImage = null;
            this.bXemDiem.IndicateFocus = false;
            this.bXemDiem.Location = new System.Drawing.Point(25, 533);
            this.bXemDiem.Name = "bXemDiem";
            this.bXemDiem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bXemDiem.OnDisabledState.BorderRadius = 1;
            this.bXemDiem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXemDiem.OnDisabledState.BorderThickness = 1;
            this.bXemDiem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bXemDiem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bXemDiem.OnDisabledState.IconLeftImage = null;
            this.bXemDiem.OnDisabledState.IconRightImage = null;
            this.bXemDiem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bXemDiem.onHoverState.BorderRadius = 1;
            this.bXemDiem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXemDiem.onHoverState.BorderThickness = 1;
            this.bXemDiem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bXemDiem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bXemDiem.onHoverState.IconLeftImage = null;
            this.bXemDiem.onHoverState.IconRightImage = null;
            this.bXemDiem.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bXemDiem.OnIdleState.BorderRadius = 1;
            this.bXemDiem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXemDiem.OnIdleState.BorderThickness = 1;
            this.bXemDiem.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bXemDiem.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bXemDiem.OnIdleState.IconLeftImage = null;
            this.bXemDiem.OnIdleState.IconRightImage = null;
            this.bXemDiem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bXemDiem.OnPressedState.BorderRadius = 1;
            this.bXemDiem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bXemDiem.OnPressedState.BorderThickness = 1;
            this.bXemDiem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bXemDiem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bXemDiem.OnPressedState.IconLeftImage = null;
            this.bXemDiem.OnPressedState.IconRightImage = null;
            this.bXemDiem.Size = new System.Drawing.Size(225, 60);
            this.bXemDiem.TabIndex = 7;
            this.bXemDiem.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bXemDiem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bXemDiem.TextMarginLeft = 0;
            this.bXemDiem.TextPadding = new System.Windows.Forms.Padding(0);
            this.bXemDiem.UseDefaultRadiusAndThickness = true;
            this.bXemDiem.Click += new System.EventHandler(this.bXemDiem_Click);
            // 
            // bBangDiem
            // 
            this.bBangDiem.AllowAnimations = true;
            this.bBangDiem.AllowMouseEffects = true;
            this.bBangDiem.AllowToggling = false;
            this.bBangDiem.AnimationSpeed = 200;
            this.bBangDiem.AutoGenerateColors = false;
            this.bBangDiem.AutoRoundBorders = false;
            this.bBangDiem.AutoSizeLeftIcon = true;
            this.bBangDiem.AutoSizeRightIcon = true;
            this.bBangDiem.BackColor = System.Drawing.Color.Transparent;
            this.bBangDiem.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bBangDiem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bBangDiem.BackgroundImage")));
            this.bBangDiem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bBangDiem.ButtonText = "Bảng điểm";
            this.bBangDiem.ButtonTextMarginLeft = 0;
            this.bBangDiem.ColorContrastOnClick = 45;
            this.bBangDiem.ColorContrastOnHover = 45;
            this.bBangDiem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bBangDiem.CustomizableEdges = borderEdges4;
            this.bBangDiem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bBangDiem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bBangDiem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bBangDiem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bBangDiem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bBangDiem.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.bBangDiem.ForeColor = System.Drawing.Color.White;
            this.bBangDiem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bBangDiem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bBangDiem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bBangDiem.IconMarginLeft = 11;
            this.bBangDiem.IconPadding = 10;
            this.bBangDiem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bBangDiem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bBangDiem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bBangDiem.IconSize = 25;
            this.bBangDiem.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bBangDiem.IdleBorderRadius = 1;
            this.bBangDiem.IdleBorderThickness = 1;
            this.bBangDiem.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bBangDiem.IdleIconLeftImage = null;
            this.bBangDiem.IdleIconRightImage = null;
            this.bBangDiem.IndicateFocus = false;
            this.bBangDiem.Location = new System.Drawing.Point(25, 467);
            this.bBangDiem.Name = "bBangDiem";
            this.bBangDiem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bBangDiem.OnDisabledState.BorderRadius = 1;
            this.bBangDiem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bBangDiem.OnDisabledState.BorderThickness = 1;
            this.bBangDiem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bBangDiem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bBangDiem.OnDisabledState.IconLeftImage = null;
            this.bBangDiem.OnDisabledState.IconRightImage = null;
            this.bBangDiem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bBangDiem.onHoverState.BorderRadius = 1;
            this.bBangDiem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bBangDiem.onHoverState.BorderThickness = 1;
            this.bBangDiem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bBangDiem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bBangDiem.onHoverState.IconLeftImage = null;
            this.bBangDiem.onHoverState.IconRightImage = null;
            this.bBangDiem.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bBangDiem.OnIdleState.BorderRadius = 1;
            this.bBangDiem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bBangDiem.OnIdleState.BorderThickness = 1;
            this.bBangDiem.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bBangDiem.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bBangDiem.OnIdleState.IconLeftImage = null;
            this.bBangDiem.OnIdleState.IconRightImage = null;
            this.bBangDiem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bBangDiem.OnPressedState.BorderRadius = 1;
            this.bBangDiem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bBangDiem.OnPressedState.BorderThickness = 1;
            this.bBangDiem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bBangDiem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bBangDiem.OnPressedState.IconLeftImage = null;
            this.bBangDiem.OnPressedState.IconRightImage = null;
            this.bBangDiem.Size = new System.Drawing.Size(225, 60);
            this.bBangDiem.TabIndex = 6;
            this.bBangDiem.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bBangDiem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bBangDiem.TextMarginLeft = 0;
            this.bBangDiem.TextPadding = new System.Windows.Forms.Padding(0);
            this.bBangDiem.UseDefaultRadiusAndThickness = true;
            this.bBangDiem.Click += new System.EventHandler(this.bBangDiem_Click);
            // 
            // bPhong
            // 
            this.bPhong.AllowAnimations = true;
            this.bPhong.AllowMouseEffects = true;
            this.bPhong.AllowToggling = false;
            this.bPhong.AnimationSpeed = 200;
            this.bPhong.AutoGenerateColors = false;
            this.bPhong.AutoRoundBorders = false;
            this.bPhong.AutoSizeLeftIcon = true;
            this.bPhong.AutoSizeRightIcon = true;
            this.bPhong.BackColor = System.Drawing.Color.Transparent;
            this.bPhong.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bPhong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bPhong.BackgroundImage")));
            this.bPhong.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bPhong.ButtonText = "Phòng";
            this.bPhong.ButtonTextMarginLeft = 0;
            this.bPhong.ColorContrastOnClick = 45;
            this.bPhong.ColorContrastOnHover = 45;
            this.bPhong.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bPhong.CustomizableEdges = borderEdges5;
            this.bPhong.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bPhong.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bPhong.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bPhong.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bPhong.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bPhong.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.bPhong.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bPhong.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bPhong.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bPhong.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bPhong.IconMarginLeft = 11;
            this.bPhong.IconPadding = 10;
            this.bPhong.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bPhong.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bPhong.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bPhong.IconSize = 25;
            this.bPhong.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bPhong.IdleBorderRadius = 1;
            this.bPhong.IdleBorderThickness = 1;
            this.bPhong.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bPhong.IdleIconLeftImage = null;
            this.bPhong.IdleIconRightImage = null;
            this.bPhong.IndicateFocus = false;
            this.bPhong.Location = new System.Drawing.Point(25, 401);
            this.bPhong.Name = "bPhong";
            this.bPhong.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bPhong.OnDisabledState.BorderRadius = 1;
            this.bPhong.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bPhong.OnDisabledState.BorderThickness = 1;
            this.bPhong.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bPhong.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bPhong.OnDisabledState.IconLeftImage = null;
            this.bPhong.OnDisabledState.IconRightImage = null;
            this.bPhong.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bPhong.onHoverState.BorderRadius = 1;
            this.bPhong.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bPhong.onHoverState.BorderThickness = 1;
            this.bPhong.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bPhong.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bPhong.onHoverState.IconLeftImage = null;
            this.bPhong.onHoverState.IconRightImage = null;
            this.bPhong.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bPhong.OnIdleState.BorderRadius = 1;
            this.bPhong.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bPhong.OnIdleState.BorderThickness = 1;
            this.bPhong.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.bPhong.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bPhong.OnIdleState.IconLeftImage = null;
            this.bPhong.OnIdleState.IconRightImage = null;
            this.bPhong.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bPhong.OnPressedState.BorderRadius = 1;
            this.bPhong.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bPhong.OnPressedState.BorderThickness = 1;
            this.bPhong.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bPhong.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bPhong.OnPressedState.IconLeftImage = null;
            this.bPhong.OnPressedState.IconRightImage = null;
            this.bPhong.Size = new System.Drawing.Size(225, 60);
            this.bPhong.TabIndex = 4;
            this.bPhong.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bPhong.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bPhong.TextMarginLeft = 0;
            this.bPhong.TextPadding = new System.Windows.Forms.Padding(0);
            this.bPhong.UseDefaultRadiusAndThickness = true;
            this.bPhong.Click += new System.EventHandler(this.bPhong_Click);
            // 
            // bHocPhan
            // 
            this.bHocPhan.AllowAnimations = true;
            this.bHocPhan.AllowMouseEffects = true;
            this.bHocPhan.AllowToggling = false;
            this.bHocPhan.AnimationSpeed = 200;
            this.bHocPhan.AutoGenerateColors = false;
            this.bHocPhan.AutoRoundBorders = false;
            this.bHocPhan.AutoSizeLeftIcon = true;
            this.bHocPhan.AutoSizeRightIcon = true;
            this.bHocPhan.BackColor = System.Drawing.Color.Transparent;
            this.bHocPhan.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bHocPhan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bHocPhan.BackgroundImage")));
            this.bHocPhan.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHocPhan.ButtonText = "Học phần";
            this.bHocPhan.ButtonTextMarginLeft = 0;
            this.bHocPhan.ColorContrastOnClick = 45;
            this.bHocPhan.ColorContrastOnHover = 45;
            this.bHocPhan.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bHocPhan.CustomizableEdges = borderEdges6;
            this.bHocPhan.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bHocPhan.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bHocPhan.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bHocPhan.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bHocPhan.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bHocPhan.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.bHocPhan.ForeColor = System.Drawing.Color.White;
            this.bHocPhan.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bHocPhan.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bHocPhan.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bHocPhan.IconMarginLeft = 11;
            this.bHocPhan.IconPadding = 10;
            this.bHocPhan.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bHocPhan.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bHocPhan.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bHocPhan.IconSize = 25;
            this.bHocPhan.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bHocPhan.IdleBorderRadius = 1;
            this.bHocPhan.IdleBorderThickness = 1;
            this.bHocPhan.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bHocPhan.IdleIconLeftImage = null;
            this.bHocPhan.IdleIconRightImage = null;
            this.bHocPhan.IndicateFocus = false;
            this.bHocPhan.Location = new System.Drawing.Point(25, 335);
            this.bHocPhan.Name = "bHocPhan";
            this.bHocPhan.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bHocPhan.OnDisabledState.BorderRadius = 1;
            this.bHocPhan.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHocPhan.OnDisabledState.BorderThickness = 1;
            this.bHocPhan.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bHocPhan.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bHocPhan.OnDisabledState.IconLeftImage = null;
            this.bHocPhan.OnDisabledState.IconRightImage = null;
            this.bHocPhan.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bHocPhan.onHoverState.BorderRadius = 1;
            this.bHocPhan.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHocPhan.onHoverState.BorderThickness = 1;
            this.bHocPhan.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bHocPhan.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bHocPhan.onHoverState.IconLeftImage = null;
            this.bHocPhan.onHoverState.IconRightImage = null;
            this.bHocPhan.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bHocPhan.OnIdleState.BorderRadius = 1;
            this.bHocPhan.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHocPhan.OnIdleState.BorderThickness = 1;
            this.bHocPhan.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bHocPhan.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bHocPhan.OnIdleState.IconLeftImage = null;
            this.bHocPhan.OnIdleState.IconRightImage = null;
            this.bHocPhan.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bHocPhan.OnPressedState.BorderRadius = 1;
            this.bHocPhan.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bHocPhan.OnPressedState.BorderThickness = 1;
            this.bHocPhan.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bHocPhan.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bHocPhan.OnPressedState.IconLeftImage = null;
            this.bHocPhan.OnPressedState.IconRightImage = null;
            this.bHocPhan.Size = new System.Drawing.Size(225, 60);
            this.bHocPhan.TabIndex = 3;
            this.bHocPhan.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bHocPhan.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bHocPhan.TextMarginLeft = 0;
            this.bHocPhan.TextPadding = new System.Windows.Forms.Padding(0);
            this.bHocPhan.UseDefaultRadiusAndThickness = true;
            this.bHocPhan.Click += new System.EventHandler(this.bHocPhan_Click);
            // 
            // bSinhVien
            // 
            this.bSinhVien.AllowAnimations = true;
            this.bSinhVien.AllowMouseEffects = true;
            this.bSinhVien.AllowToggling = false;
            this.bSinhVien.AnimationSpeed = 200;
            this.bSinhVien.AutoGenerateColors = false;
            this.bSinhVien.AutoRoundBorders = false;
            this.bSinhVien.AutoSizeLeftIcon = true;
            this.bSinhVien.AutoSizeRightIcon = true;
            this.bSinhVien.BackColor = System.Drawing.Color.Transparent;
            this.bSinhVien.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bSinhVien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bSinhVien.BackgroundImage")));
            this.bSinhVien.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSinhVien.ButtonText = "Sinh viên";
            this.bSinhVien.ButtonTextMarginLeft = 0;
            this.bSinhVien.ColorContrastOnClick = 45;
            this.bSinhVien.ColorContrastOnHover = 45;
            this.bSinhVien.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bSinhVien.CustomizableEdges = borderEdges7;
            this.bSinhVien.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bSinhVien.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bSinhVien.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bSinhVien.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bSinhVien.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bSinhVien.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.bSinhVien.ForeColor = System.Drawing.Color.White;
            this.bSinhVien.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bSinhVien.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bSinhVien.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bSinhVien.IconMarginLeft = 11;
            this.bSinhVien.IconPadding = 10;
            this.bSinhVien.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bSinhVien.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bSinhVien.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bSinhVien.IconSize = 25;
            this.bSinhVien.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bSinhVien.IdleBorderRadius = 1;
            this.bSinhVien.IdleBorderThickness = 1;
            this.bSinhVien.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bSinhVien.IdleIconLeftImage = null;
            this.bSinhVien.IdleIconRightImage = null;
            this.bSinhVien.IndicateFocus = false;
            this.bSinhVien.Location = new System.Drawing.Point(25, 203);
            this.bSinhVien.Name = "bSinhVien";
            this.bSinhVien.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bSinhVien.OnDisabledState.BorderRadius = 1;
            this.bSinhVien.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSinhVien.OnDisabledState.BorderThickness = 1;
            this.bSinhVien.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bSinhVien.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bSinhVien.OnDisabledState.IconLeftImage = null;
            this.bSinhVien.OnDisabledState.IconRightImage = null;
            this.bSinhVien.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bSinhVien.onHoverState.BorderRadius = 1;
            this.bSinhVien.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSinhVien.onHoverState.BorderThickness = 1;
            this.bSinhVien.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bSinhVien.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bSinhVien.onHoverState.IconLeftImage = null;
            this.bSinhVien.onHoverState.IconRightImage = null;
            this.bSinhVien.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bSinhVien.OnIdleState.BorderRadius = 1;
            this.bSinhVien.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSinhVien.OnIdleState.BorderThickness = 1;
            this.bSinhVien.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bSinhVien.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bSinhVien.OnIdleState.IconLeftImage = null;
            this.bSinhVien.OnIdleState.IconRightImage = null;
            this.bSinhVien.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bSinhVien.OnPressedState.BorderRadius = 1;
            this.bSinhVien.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bSinhVien.OnPressedState.BorderThickness = 1;
            this.bSinhVien.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bSinhVien.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bSinhVien.OnPressedState.IconLeftImage = null;
            this.bSinhVien.OnPressedState.IconRightImage = null;
            this.bSinhVien.Size = new System.Drawing.Size(225, 60);
            this.bSinhVien.TabIndex = 2;
            this.bSinhVien.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bSinhVien.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bSinhVien.TextMarginLeft = 0;
            this.bSinhVien.TextPadding = new System.Windows.Forms.Padding(0);
            this.bSinhVien.UseDefaultRadiusAndThickness = true;
            this.bSinhVien.Click += new System.EventHandler(this.bSinhVien_Click);
            // 
            // bTongQuan
            // 
            this.bTongQuan.AllowAnimations = true;
            this.bTongQuan.AllowMouseEffects = true;
            this.bTongQuan.AllowToggling = false;
            this.bTongQuan.AnimationSpeed = 200;
            this.bTongQuan.AutoGenerateColors = false;
            this.bTongQuan.AutoRoundBorders = false;
            this.bTongQuan.AutoSizeLeftIcon = true;
            this.bTongQuan.AutoSizeRightIcon = true;
            this.bTongQuan.BackColor = System.Drawing.Color.Transparent;
            this.bTongQuan.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bTongQuan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bTongQuan.BackgroundImage")));
            this.bTongQuan.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bTongQuan.ButtonText = "Tổng quan";
            this.bTongQuan.ButtonTextMarginLeft = 0;
            this.bTongQuan.ColorContrastOnClick = 45;
            this.bTongQuan.ColorContrastOnHover = 45;
            this.bTongQuan.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bTongQuan.CustomizableEdges = borderEdges8;
            this.bTongQuan.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bTongQuan.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bTongQuan.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bTongQuan.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bTongQuan.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bTongQuan.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.bTongQuan.ForeColor = System.Drawing.Color.White;
            this.bTongQuan.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bTongQuan.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bTongQuan.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bTongQuan.IconMarginLeft = 11;
            this.bTongQuan.IconPadding = 10;
            this.bTongQuan.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bTongQuan.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bTongQuan.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bTongQuan.IconSize = 25;
            this.bTongQuan.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bTongQuan.IdleBorderRadius = 1;
            this.bTongQuan.IdleBorderThickness = 1;
            this.bTongQuan.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bTongQuan.IdleIconLeftImage = null;
            this.bTongQuan.IdleIconRightImage = null;
            this.bTongQuan.IndicateFocus = false;
            this.bTongQuan.Location = new System.Drawing.Point(25, 137);
            this.bTongQuan.Name = "bTongQuan";
            this.bTongQuan.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bTongQuan.OnDisabledState.BorderRadius = 1;
            this.bTongQuan.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bTongQuan.OnDisabledState.BorderThickness = 1;
            this.bTongQuan.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bTongQuan.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bTongQuan.OnDisabledState.IconLeftImage = null;
            this.bTongQuan.OnDisabledState.IconRightImage = null;
            this.bTongQuan.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bTongQuan.onHoverState.BorderRadius = 1;
            this.bTongQuan.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bTongQuan.onHoverState.BorderThickness = 1;
            this.bTongQuan.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bTongQuan.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bTongQuan.onHoverState.IconLeftImage = null;
            this.bTongQuan.onHoverState.IconRightImage = null;
            this.bTongQuan.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bTongQuan.OnIdleState.BorderRadius = 1;
            this.bTongQuan.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bTongQuan.OnIdleState.BorderThickness = 1;
            this.bTongQuan.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bTongQuan.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bTongQuan.OnIdleState.IconLeftImage = null;
            this.bTongQuan.OnIdleState.IconRightImage = null;
            this.bTongQuan.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bTongQuan.OnPressedState.BorderRadius = 1;
            this.bTongQuan.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bTongQuan.OnPressedState.BorderThickness = 1;
            this.bTongQuan.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bTongQuan.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bTongQuan.OnPressedState.IconLeftImage = null;
            this.bTongQuan.OnPressedState.IconRightImage = null;
            this.bTongQuan.Size = new System.Drawing.Size(225, 60);
            this.bTongQuan.TabIndex = 1;
            this.bTongQuan.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bTongQuan.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bTongQuan.TextMarginLeft = 0;
            this.bTongQuan.TextPadding = new System.Windows.Forms.Padding(0);
            this.bTongQuan.UseDefaultRadiusAndThickness = true;
            this.bTongQuan.Click += new System.EventHandler(this.bTongQuan_Click);
            // 
            // pTop1
            // 
            this.pTop1.BackgroundColor = System.Drawing.SystemColors.Control;
            this.pTop1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pTop1.BackgroundImage")));
            this.pTop1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pTop1.BorderColor = System.Drawing.Color.Transparent;
            this.pTop1.BorderRadius = 0;
            this.pTop1.BorderThickness = 0;
            this.pTop1.Controls.Add(this.lTop);
            this.pTop1.Dock = System.Windows.Forms.DockStyle.Top;
            this.pTop1.Location = new System.Drawing.Point(250, 0);
            this.pTop1.Name = "pTop1";
            this.pTop1.ShowBorders = false;
            this.pTop1.Size = new System.Drawing.Size(1030, 50);
            this.pTop1.TabIndex = 2;
            // 
            // lTop
            // 
            this.lTop.AllowParentOverrides = false;
            this.lTop.AutoEllipsis = false;
            this.lTop.Cursor = System.Windows.Forms.Cursors.Default;
            this.lTop.CursorType = System.Windows.Forms.Cursors.Default;
            this.lTop.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.lTop.ForeColor = System.Drawing.Color.DodgerBlue;
            this.lTop.Location = new System.Drawing.Point(6, 12);
            this.lTop.Name = "lTop";
            this.lTop.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lTop.Size = new System.Drawing.Size(841, 34);
            this.lTop.TabIndex = 0;
            this.lTop.Text = "MTA Management System ♥ 236 Hoàng Quốc Việt, Cầu Giấy, Hà Nội";
            this.lTop.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lTop.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pTop2
            // 
            this.pTop2.BackgroundColor = System.Drawing.Color.DodgerBlue;
            this.pTop2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pTop2.BackgroundImage")));
            this.pTop2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pTop2.BorderColor = System.Drawing.Color.Transparent;
            this.pTop2.BorderRadius = 0;
            this.pTop2.BorderThickness = 0;
            this.pTop2.Controls.Add(this.lTime);
            this.pTop2.Controls.Add(this.lName);
            this.pTop2.Controls.Add(this.lXinChao);
            this.pTop2.Location = new System.Drawing.Point(250, 56);
            this.pTop2.Name = "pTop2";
            this.pTop2.ShowBorders = false;
            this.pTop2.Size = new System.Drawing.Size(1030, 81);
            this.pTop2.TabIndex = 3;
            // 
            // lTime
            // 
            this.lTime.AllowParentOverrides = false;
            this.lTime.AutoEllipsis = false;
            this.lTime.CursorType = null;
            this.lTime.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.lTime.ForeColor = System.Drawing.SystemColors.Control;
            this.lTime.Location = new System.Drawing.Point(822, 26);
            this.lTime.Name = "lTime";
            this.lTime.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lTime.Size = new System.Drawing.Size(126, 34);
            this.lTime.TabIndex = 2;
            this.lTime.Text = "HH:mm:ss";
            this.lTime.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lTime.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lName
            // 
            this.lName.AllowParentOverrides = false;
            this.lName.AutoEllipsis = false;
            this.lName.CursorType = null;
            this.lName.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.lName.ForeColor = System.Drawing.SystemColors.Control;
            this.lName.Location = new System.Drawing.Point(143, 26);
            this.lName.Name = "lName";
            this.lName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lName.Size = new System.Drawing.Size(171, 34);
            this.lName.TabIndex = 1;
            this.lName.Text = "Nguyễn Văn A";
            this.lName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lXinChao
            // 
            this.lXinChao.AllowParentOverrides = false;
            this.lXinChao.AutoEllipsis = false;
            this.lXinChao.Cursor = System.Windows.Forms.Cursors.Default;
            this.lXinChao.CursorType = System.Windows.Forms.Cursors.Default;
            this.lXinChao.Font = new System.Drawing.Font("Open Sans", 15F, System.Drawing.FontStyle.Bold);
            this.lXinChao.ForeColor = System.Drawing.SystemColors.Control;
            this.lXinChao.Location = new System.Drawing.Point(24, 26);
            this.lXinChao.Name = "lXinChao";
            this.lXinChao.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lXinChao.Size = new System.Drawing.Size(113, 34);
            this.lXinChao.TabIndex = 0;
            this.lXinChao.Text = "Xin chào,";
            this.lXinChao.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lXinChao.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // dcDashboard
            // 
            this.dcDashboard.Fixed = true;
            this.dcDashboard.Horizontal = true;
            this.dcDashboard.TargetControl = this.pTop1;
            this.dcDashboard.Vertical = true;
            // 
            // pUserControl
            // 
            this.pUserControl.BackgroundColor = System.Drawing.Color.Transparent;
            this.pUserControl.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pUserControl.BackgroundImage")));
            this.pUserControl.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pUserControl.BorderColor = System.Drawing.Color.Transparent;
            this.pUserControl.BorderRadius = 0;
            this.pUserControl.BorderThickness = 0;
            this.pUserControl.Location = new System.Drawing.Point(250, 137);
            this.pUserControl.Name = "pUserControl";
            this.pUserControl.ShowBorders = true;
            this.pUserControl.Size = new System.Drawing.Size(1030, 580);
            this.pUserControl.TabIndex = 5;
            // 
            // FDashboard
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.ClientSize = new System.Drawing.Size(1280, 720);
            this.Controls.Add(this.pUserControl);
            this.Controls.Add(this.pTop2);
            this.Controls.Add(this.pTop1);
            this.Controls.Add(this.pLeft);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FDashboard";
            this.Text = "FDashboard";
            this.pLeft.ResumeLayout(false);
            this.pLeft.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pbLogo)).EndInit();
            this.pTop1.ResumeLayout(false);
            this.pTop1.PerformLayout();
            this.pTop2.ResumeLayout(false);
            this.pTop2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel pLeft;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bPhong;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bHocPhan;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bSinhVien;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bTongQuan;
        private Bunifu.UI.WinForms.BunifuPanel pSlider;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bDangXuat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bXemDiem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bBangDiem;
        private Bunifu.UI.WinForms.BunifuPictureBox pbLogo;
        private Bunifu.UI.WinForms.BunifuLabel lLogo;
        private Bunifu.UI.WinForms.BunifuSeparator sLeft;
        private Bunifu.UI.WinForms.BunifuPanel pTop1;
        private Bunifu.UI.WinForms.BunifuLabel lTop;
        private Bunifu.UI.WinForms.BunifuPanel pTop2;
        private Bunifu.UI.WinForms.BunifuLabel lTime;
        private Bunifu.UI.WinForms.BunifuLabel lName;
        private Bunifu.UI.WinForms.BunifuLabel lXinChao;
        private Bunifu.Framework.UI.BunifuDragControl dcDashboard;
        private System.Windows.Forms.Timer timer1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bLop;
        private Bunifu.UI.WinForms.BunifuPanel pUserControl;
    }
}